### ISSUE TITLE
spm doc watch 时，如何保持可以访问 *.md 源文件

### ISSUE THREAD

**Issue by hotoo** [spmjs/spm#1030]
在做一个基于 markdown 的模块，数据部分来自 markdown，但是现在 *.md 只能通过 * （不带 .md 后缀）直接访问，而且被转成 html。

是否可以提供直接访问 *.md 源码的访问？

比如访问 `*.md` 则返回源码，或者类似 `?nowrap` 参数什么的。

**Comment by sorrycc** [comment]
静态化后，.md 源文件彻底不能访问了。。

**Comment by hotoo** [comment]
好吧，看来只能直接 cp 一份了。
