### ISSUE TITLE
npm install spm -g 安装出错

### ISSUE THREAD

**Issue by blueforest** [spmjs/spm#1035]
系统:mac
node版本:v0.10.22
第一次执行:npm install spm -g
错误信息:
npm http GET https://registry.npmjs.org/spm
npm http 304 https://registry.npmjs.org/spm
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/spm'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/spm']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/spm',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/spm',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

第二次执行:sudo npm install -g spm

错误信息：
npm http 304 https://registry.npmjs.org/amdefine
npm ERR! phantomjs@1.9.10 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.10 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "spm"
npm ERR! cwd /Users/blueforest
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/blueforest/npm-debug.log
npm ERR! not ok code 0

**Comment by batizhao** [comment]
sudo chown -R $USER /usr/local
sudo chown -R $USER ~/.npm
npm install -g spm
