### ISSUE TITLE
我有好多关于spm的问题。。。

### ISSUE THREAD

**Issue by goodwinfame** [spmjs/spm#1039]
想在alice的基础上搭一个自己的样式库，就是类似于这个页面的http://aliceui.org/stylib/
试了很久，基本上每一步都会遇到问题，有些自己查查可以解决，有些查不到
想集中起来问一下，希望大神帮忙。
1.如何使用spm下载整个sea-modules到本地
不知是否我理解问题，arale文档上写的是用spm install下载整个sea-modules？我试了下不行

2.用spm下载单个包的时候也有问题
例如直接用spm install alice是可以下载的
但是如果用spm install arale就不可以
就是安装里面的position， 也不能直接使用spm install arale/position安装
必须加上@1.0.0版本号才能装，而且版本号错了还安装不了，可是我不知道最新的版本号是多少，怎么装最新的呢？
其他的一些包我试了各种方式，加上版本号也装不了。。不知道是不是我操作有问题。

3.本地建的模块，用spm doc watch可以预览对吗，但是如何正确引用依赖呢
按照alice网站的文档，我建了个box，在package.json中添加了alice的box依赖
这个依赖应该指的是alice框架中的box样式对吗？
但是我使用doc watch，我的box页面却没有加载alice的box样式。
我已经将alice下载到本地，但是不知道如何设置正确路径，本地上应该怎么做呢
如果将我的项目或静态页面提交到源上，这个路径又该如何配置呢

4.已经建好模块，例如版本号1.0.0
此时我提交到源上，但如果修改了内容，如何使用spm命令修改版本号或其他信息呢？
如果要更新只需要再提交一次就可以了吗？

5.有没有哪位大神愿意给个QQ号，或者QQ群我，希望详细学习。

谢谢大家

**Comment by fancyboynet** [comment]
同求扣扣群
