### ISSUE TITLE
如何配置无idleading

### ISSUE THREAD

**Issue by kerryChen95** [spmjs/spm#1055]
默认的 `idloading` 为 `{{name}}/{{version}}` ，对于通用的package来说，是合理的，但是对于使用Sea.js来组织模块化的业务项目来说，可能就不需要这样的前缀（因为更倾向于使用根据文件内容计算出的md5值作为版本信息）。

目前只能通过 `--idleading {{}}` 来实现无 `idleading` ，尝试过 `--idleading \"\"` 或 `--idleading \'\'` 或 `--idloading` 都提示 `error: option '--idleading <idleading>' argument missing` ，但觉得用 `{{}}` 这样的方式很反自觉，文档里也没说如何配置无idleading的情况。

所以，是不是可以通过 `spm build --idleading` 这样来配置无idleading。

题外话：
感觉spm主要是为构建通用模块而设计，对于使用Sea.js来组织模块化的业务项目，设计上的考虑可能少些。不知道是不是spm的定位就是主要为构建通用模块而服务的，如果是的话，如果不能在业务项目中很方便的使用起这些通用模块，可能也不太好。

---

P.S. 提个醒，spm3输出的错误信息

```
option `--idleading <idleading>' argument missing
```

前面用的是反引号，后面用的是单引号。应该是个typo

**Comment by crossjs** [comment]
3.3.4

```
$ spm build --idleading ''
```

还是会生成一个 `''` 目录。

**Comment by sorrycc** [comment]
场景是什么，为啥要把 idleading 设为空 ?
