### ISSUE TITLE
讨论：include 相关

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1086]
## 简化

出于以下的考虑：

1. include 模式有点多：self、relative、all、standalone、umd，其中前三个都是和 seajs 相关的。现在 standalone 模式已经能适应各种项目模式的需求了，感觉可以弱化使用 seajs 的方案
1. 在推广 spm 时，能感受到大家对于理解 include 的各种模式有些困难，解释起来也不是很方便
1. standalone, umd 并不是一种`文件合并`的方式，感觉放在 include 里并不合适

建议：

1. spm 宣传层面去掉 `--include` 参数，改换成 `--sea`, `--standalone` 和 `--umd`。`--sea` 即 `--include relative`
1. 底层 (gulp-spm) 仍保留对 self 和 all 的支持，便于特殊场景自行实现构建

## 默认 standalone

从目前的使用情况来看，sea 的打包方式更多是在构建组件发布到 cdn 时使用；而对于大部分项目来说，standalone 则是首选。

另外，默认 standalone 对于新手来说会更友好，可以用类似 duojs/browserify 的方式来使用 spm ，推广起来也更简单。

使用 spm 的步骤：

1. 编辑 js 代码并保存
1. 构建你所需的文件，比如 `$ spm build entry.js > build.js`
1. 在 HTML 中引用 build.js

DEMO：

![](https://t.alipayobjects.com/images/T1jk8dXhdxXXXXXXXX.gif)

**Comment by sorrycc** [comment]
默认 standalone 是个不兼容的方案：现有包很多都没配 `--include`，如果改成默认 standalone，打包出来的结果不对。尤其是对云构建平台来说。

**Comment by popomore** [comment]
4.0 :smile:

**Comment by hotoo** [comment]
--sea 改成 --cmd 是不是合适点？

**Comment by afc163** [comment]
cmd 在命令行会有歧义。

**Comment by afc163** [comment]
`spm build entry.js > build.js` 的方式现在已经支持了吗？我之前使用好像发现这命令修改了 package.json 里的模块版本。

**Comment by sorrycc** [comment]
支持 `spm build entry.js`，但不支持 `spm build entry.js > build.js`。

https://github.com/spmjs/spm-build/blob/master/lib/build.js#L50
确实会修改，是个 bug 。

2015-01-15 0:26 GMT+08:00 偏右 <notifications@github.com>:

**Comment by sorrycc** [comment]
简化部分已完成，默认 standalone 近期应该是做不了的。

**Comment by afc163** [comment]
参数中出现 --include 时，命令行里给出简单的改动提示吧。

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/5934204/cad94ab4-a706-11e4-900c-c7731570f83a.png)

给了。
