### ISSUE TITLE
scripts 支持

### ISSUE THREAD

**Issue by popomore** [spmjs/spm#1097]
#1092 里提到的场景可能有些特殊，但支持能增大开发体验。

尤其在和 npm 同步的时候，比如 flux 在 publish 设了 prepublish 将 es6 转 es5，但是在 spm 中就没有这个功能就会遗忘。

**Comment by afc163** [comment]
scripts 重造了 npm 的轮子啊，我们只需要支持 build 就够用了。

**Comment by popomore** [comment]
现在做 build，如果简单就都支持了

**Comment by sorrycc** [comment]
先支持以下几个 scripts 吧：

* prepublish, postpublish
* prebuild, build, postbuild

**Comment by afc163** [comment]
preinstall postinstall
