### ISSUE TITLE
spm test 不能使用

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#1106]
版本：3.3

运行 spm test 后只有：

```

  Starting service for test runner ...
```

**Comment by afc163** [comment]
@sorrycc

**Comment by sorrycc** [comment]
https://github.com/fishbar/jscoverage/blob/master/lib/patch.js#L53-L89
这部分代码导致的，考虑直接切换到 istanbul 或 node-jscover 了。

#1087

**Comment by afc163** [comment]
哦，原来是升了版本的问题，我先降回来。后续再更换。

**Comment by sorrycc** [comment]
赞

**Comment by afc163** [comment]
早先想升级 jscoverage 来着，也是遇到奇怪的问题，就没升上去。
