### ISSUE TITLE
默认支持 es6

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1123]
* [x] spm-build
* [x] serve-spm

**Comment by army8735** [comment]
有继续讨论吗

**Comment by sorrycc** [comment]
没人反对，我找时间加上。

**Comment by popomore** [comment]
应该没有吧，es5 的代码老样子就行

**Comment by sorrycc** [comment]
直接用 6to5 吧，不一定要和 node 保持一致。

**Comment by sorrycc** [comment]
兼容表：
https://kangax.github.io/compat-table/es6/#_6to5

**Comment by afc163** [comment]
需要解决本地调试的问题。
