### ISSUE TITLE
spm build 输出多个文件

### ISSUE THREAD

**Issue by mvplinchen888** [spmjs/spm#1126]
在 [seajs官网的demo][seajs-demo] 中有4个小例子，使用的构建工具为spm2.X。拿[angularjs](https://github.com/seajs/examples/tree/master/static/ng-todo)为例：[package.json](https://github.com/seajs/examples/blob/master/static/ng-todo/package.json)文件中， spm.output属性指定了3个输出文件。  

那么问题来了：我如何在spm3.X中也输出多个文件？  这个[教程贴](https://github.com/spmjs/spm/wiki/%E8%BF%81%E7%A7%BB-spm2-%E7%9A%84%E6%A8%A1%E5%9D%97%E5%88%B0-spm3)中只有输出了一个文件。

求大神给个使用spm3.X构建[seajs官网的demo][seajs-demo]的方法！

[seajs-demo]: https://github.com/seajs/examples

**Comment by sorrycc** [comment]
看下这个，https://github.com/spmjs/examples

**Comment by mvplinchen888** [comment]
@sorrycc  3Q!   学习下。

**Comment by mvplinchen888** [comment]
我发现使用spm3的项目中不需要使用seajs。那么是不是说spm3和seajs就没有关系了？

**Comment by afc163** [comment]
可以用，推荐不用。

**Comment by hotoo** [comment]
@afc163  spm3 推荐的用法是什么？

**Comment by afc163** [comment]
是啊。

**Comment by afc163** [comment]
可以关注下：https://github.com/spmjs/spm/issues/1086
