### ISSUE TITLE
support install from npm

### ISSUE THREAD

**Issue by yiminghe** [spmjs/spm#1133]
这样就不用同步了....
```
spm install npm:rc-calendar
spm install tnpm:rc-calendar
```

```
- spm_modules
  - rc-calendar/version/index
  - gregorian-calendar/version/index
```

**Comment by popomore** [comment]
Makefile

```
publish:
  npm publish
  spm publish
```

也不用同步吧，不用 npm 的模块也不需要 publish 吧，如果想支持 npm 当时也不会做 spmjs.io 了

**Comment by afc163** [comment]
https://github.com/zeroclipboard/zeroclipboard/blob/f0263698a4123376bb46bbd814fd968f48b9def1/package.json#L80

**Comment by yiminghe** [comment]
我说第三方组件之类的，我就不用 clone 再 spm publish 了

**Comment by yiminghe** [comment]
jspm 这样挺好的，spm 开放点和他们竞争下，也更方便用了
