### ISSUE TITLE
能不能增加以下下载次数或者 star数,今天被一个有BUG的库坑了

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1137]
http://spmjs.io/package/template
这个库有错误, 名字上看好官方的感觉, 点击作者链接也是404, 花了N个小时才知道.
http://spmjs.io/package/xs.art-template
才是真爱

**Comment by afc163** [comment]
有 star 数的，比如：http://spmjs.io/package/moment/
下载数这个暂时没有，以后会加上。

**Comment by afc163** [comment]
如果某个模块有问题，也可以尝试联系模块的发布者。

**Comment by alvin2ye** [comment]
@afc163 你找错了

![](http://agi-public3.qiniudn.com/20150109182053/6.png)
![](http://agi-public3.qiniudn.com/20150109182055/7.png)

**Comment by afc163** [comment]
不是有 Owner 。

**Comment by popomore** [comment]
owner 就是发布的人，找他准没错

—
通过 Mailbox 发送

**Comment by alvin2ye** [comment]
@popomore OK
