### ISSUE TITLE
在项目用到 at.js 发现 spm 中得自带的不能用, 必须自己修改后才可以. 是我用错了吗?

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1141]
比如 jquery 的插件, 不是推荐要这么用吗?

```
var $ = require("jquery");
require("caret.js")($);
require("at.js")($);

```
我有以下问题:

- 但是看了源代码根本就是错误的, 还有代码里是直接用 window.jQuery 的, 是我用法错了吗?
- at.js 的包依赖 jquery 和 caret.js 包, 为什么不是在 at.js 包里自己写依赖, 却是在业务代码里写呢?

我自己改了源代码才可以用, 在 https://github.com/alvin2ye/example_spm3_at.js

**Comment by afc163** [comment]
这种包不规范的问题联系 Owner 就好了，或者自己发一个 `at2` 什么的。

**Comment by popomore** [comment]
haha @sorrycc

**Comment by alvin2ye** [comment]
@afc163  spm 里一大推不能用的, 对spm 的发展也很不利吧, 想直接帮他修了. 也不知道这么联系
Owner 是 @sorrycc

**Comment by sorrycc** [comment]
更新了下，可以用了，jQuery 版本需是 1.9.1，或者 ignore 掉也可以。

```
var $ = require('jquery');
require('at.js');

$('#inputor').atwho({
    at: "@",
    data:['Peter', 'Tom', 'Anne']
});
```

**Comment by sorrycc** [comment]
还有其他包不能用的?

**Comment by afc163** [comment]
生态圈就是这样，npm 也一样啊。允许差的，才有好的。

**Comment by afc163** [comment]
生态圈就是这样，npm 也一样啊。允许差的，才有好的。

**Comment by afc163** [comment]
生态圈就是这样，npm 也一样啊。允许差的，才有好的。

**Comment by afc163** [comment]
生态圈就是这样，npm 也一样良莠不齐啊。允许差的，才有好的。

**Comment by afc163** [comment]
联系当然首推邮箱啊。

**Comment by alvin2ye** [comment]
@sorrycc 强烈建议你自己试下. 现在还是坏的. 你修了 at.js 还要修它依赖的 caret.js'
看这里

```


(function() {
  (function(factory) {
    if (typeof define === 'function' && define.amd) {
      return define(['jquery'], factory);
    } else {
      return factory(window.jQuery);
    }
  })(function($) {
```

**Comment by sorrycc** [comment]
本地删 spm_modules 测了下，也是好的。caret.js 是 0.2.1，注意下。

**Comment by afc163** [comment]
`spm install -f` 会不会有缓存？

**Comment by alvin2ye** [comment]
caret.js  升级了就好了

**Comment by alvin2ye** [comment]
@sorrycc 在问下, 为什么不用
```
require("caret.js")($);
require("at.js")($);
```
的语法, 重新 require("jquery") 覆盖掉别人的 $  导致丢方法怎么办?

**Comment by popomore** [comment]
我觉得也传进去比较好

**Comment by sorrycc** [comment]
现在只是把 window.jQuery 换成 require('jquery')，传进去的话改的内容比较多，升级跟进不方便。

**Comment by alvin2ye** [comment]
最后还是自己写了at2

**Comment by afc163** [comment]
赞
