### ISSUE TITLE
`spm install --save jquery@1.11.1`，save 不生效

### ISSUE THREAD

**Issue by crossjs** [spmjs/spm#1144]
rt，指定版本号，save 无效

**Comment by alvin2ye** [comment]
package.json 有吗?

**Comment by sorrycc** [comment]
贴下命令行内容看看? 试了下没发现问题。

**Comment by crossjs** [comment]
还以为是版本太低，更新到最新后问题依旧。

前提：指定的 jquery 已存在于 spm_modules 目录下。（一般是因为先安装了一个依赖 jquery 的模块）

这种情况下，`spm install --save jquery@1.11.1`，package.json 没有被更新。
