### ISSUE TITLE
spm build 时 css 样式中的 background:none; 会被转成 background:0 0;

### ISSUE THREAD

**Issue by airyland** [spmjs/spm#1146]
如题。导致今天发现奇怪的bug，原来div被覆盖的背景颜色又回来了。

```css
background-color: rgba(0,0,0,.5);
```

**Comment by sorrycc** [comment]
检测下 debug 版本，如果 debug 版本正常的话就是 clean-css 的问题，可以找下配置项设置到 spm.cssmin 里重新构建。

https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-programmatically

**Comment by airyland** [comment]
debug版本正常

**Comment by airyland** [comment]
如何设置spm.cssmin？ 有没有文档？

试了下面的不能用。

`spm config set cssmin.advanced  false`

**Comment by sorrycc** [comment]
在 `package.json` 里配，比如：

```
{
  "name": "a",
  "version": "0.1.0",
  "spm": {
    "cssmin": {}
  }
}
```

**Comment by airyland** [comment]
试过无效。这个代码优化似乎不能配置。
https://github.com/jakubpawlowicz/clean-css/commit/9ec61247cbb5757787f14d7f073d84d3ffae23b9
