### ISSUE TITLE
doc 下不能访问到字体文件

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1148]
比如：https://github.com/react-component/menu

本地 doc 后，访问 http://localhost:8000/font-awesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0 是 404

**Comment by afc163** [comment]
这种字体文件放在本地的意义是？仅仅为了调试吗？

**Comment by sorrycc** [comment]
CSS 库包含字体文件，感觉挺正常啊。

**Comment by afc163** [comment]
才发现还有 http://spmjs.io/package/font-awesome 这个库。。

**Comment by afc163** [comment]
嗯，果然是 `static package manager` 。
