### ISSUE TITLE
test 直接使用 mocha-phantomjs

### ISSUE THREAD

**Issue by popomore** [spmjs/spm#1149]
现在 mocha-phantomjs 已经很强大了，已经没必要再用 mocha-browser 封装了。

- [x] 替换 mocha-browser
- [x] exeq 支持 promise https://github.com/afc163/exeq/issues/3
- [x] 更多测试
- [x] -cov.js 通过 doc 生成

**Comment by popomore** [comment]
有一个奇怪的问题

`mocha-phantomjs http://127.0.0.1:8015/tests/runner.html?cov` 不会输出 reporter

**Comment by afc163** [comment]
试试 `mocha-phantomjs http://127.0.0.1:8015/tests/runner.html\?cov`

**Comment by popomore** [comment]
一样的，这个转义 zsh 会处理的，reporter 好像只有 console.error

**Comment by popomore** [comment]
换一个库就可以了，dialog 有问题

**Comment by sorrycc** [comment]
dialog 为啥不行?
