### ISSUE TITLE
4.0.0

### ISSUE THREAD

**Issue by popomore** [spmjs/spm#1155]
我们接下来尽量遵循语义化版本，不要每次都发 patch 了，patch 只为了修复 bug，就算一个 commit 都可以发一个版本。基本上在 3.x 上有什么改动尽量发 minor。

建立 4.x 分支，将一些大的代码重构，以及一些比较大的接口变更都放到这上开发，比如 spmjs/spm-argv#1 和 #1086，尤其接口变更是肯定要发 major 的。

**Comment by afc163** [comment]
还是不要用 4 这个版本。

之前的版本 1 2 3 都是大的颠覆性改动，4 5 6 这些就留给后人吧。

**Comment by popomore** [comment]
其实 1 以后都可以加大版本了

**Comment by sorrycc** [comment]
4 感觉有点远了，短时间应该不会开发吧。新增一个不兼容的版本感觉会乱。

**Comment by afc163** [comment]
3.4 挺好，不够就 3.5 显得整。

**Comment by yiminghe** [comment]
如果支持 npm 和 node_modules 那么完全可以叫 4 了

**Comment by popomore** [comment]
@yiminghe 哈哈，确实
