### ISSUE TITLE
spm doc build 生成的文档如何进行站点部署？

### ISSUE THREAD

**Issue by whuhacker** [spmjs/spm#1158]
我在使用 spm 来管理内部开发文档，想将 markdown 文档生成类似 aliceui.org 和 aralejs.org 的文档站点。

本地 `spm doc watch` 测试没有问题。但当部署时，配置 nginx 将根目录指向 `spm doc build` 生成的 `_site` 目录，站点可以访问，但是依赖的组件路径有问题，http://xxx.com/arale-sticky/1.4.0/index.js 提示 404.

难道 `spm doc build` 不是生成纯静态文档站点吗？背后还是必须要有 NodeJS 才能跑起来？

**Comment by sorrycc** [comment]
现在还不是全静态的，组件这一层需要通过 serve-spm 这个中间件处理下。

2015-01-16 11:31 GMT+08:00 Zeng Xi <notifications@github.com>:

**Comment by whuhacker** [comment]
那么现在是如何部署的呢？
`spm doc watch --port 8080` 然后 nginx proxy_pass 转发到 8080 端口？
还要开一个守护进程保证 spm doc watch 不要挂掉……

**Comment by yiminghe** [comment]
希望全部静态化

**Comment by popomore** [comment]
恩，我也希望静态化

**Comment by hotoo** [comment]
现在用 standalone 不是可以进行静态化了么

**Comment by whuhacker** [comment]
@hotoo  可以详细解释一下吗？什么 standalone？

**Comment by afc163** [comment]
spm doc 生成的站点，目前本地调试和线上部署的都是同一份 CommonJS 的源码，都需要用 serve-spm 来处理才能跑起来。

之前没能静态化的原因之一是本地调试和构建速度的矛盾（尤其是文件比较多的时候）。现在想想其实可以把 `spm doc build` 和 `spm doc watch` 的代码分开，watch 的代码是源码，build 的代码是可直接运行的 CMD 代码。

PS：楼主是我研究生的师弟...

**Comment by whuhacker** [comment]
我有考虑直接用 nico 来生产文档，不过就不如现在 spm doc 简便，还得自己写个主题。

PS. `spm doc` 依赖的 `nico` 工具作者小明是我公司前同事……

**Comment by afc163** [comment]
也是我们的前同事。。

**Comment by whuhacker** [comment]
Any update on this issue?

**Comment by sorrycc** [comment]
已经静态化，spm@3.6 。

**Comment by whuhacker** [comment]
@sorrycc 
看了一下，spm 3.6 在我的原项目下 `spm doc build` 生成 `_site` 目录，仍然提示 http://xxx.com/arale-sticky/1.4.0/index.js 404.

原项目使用了和  aliceui.org 一样的 template，怎样才能生成静态页呢……？
