### ISSUE TITLE
spm check

### ISSUE THREAD

**Issue by popomore** [spmjs/spm#1159]
提供一个工具可以校验包是否正确

**Comment by sorrycc** [comment]
检查啥? 想了想好想只有 package.json 的 name, version 和 spm 这些属性，代码层面的好像没什么硬性要求。

**Comment by popomore** [comment]
比如 main 是不是存在，是否有 require 而没有配依赖的，跑个基线的测试用例是否成功 exports 了



—
通过 Mailbox 发送

**Comment by afc163** [comment]
可以先作为独立的 bin 来提供，不要集成进来，感觉只是个非必需的辅助工具。

**Comment by popomore** [comment]
是的

**Comment by popomore** [comment]
不过对外部转进来的包很有用

**Comment by afc163** [comment]
包括可以提前列出要 publish 的包的内容和大小，方便 ignore 。

**Comment by popomore** [comment]
https://github.com/timoxley/pkgfiles/issues/4

**Comment by hotoo** [comment]
* 项目开发时，一般使用 output 而不是 main 的。
* 有 require 没有配置依赖好像 build 的时候自动会加（被加过 import-style），是不是可以像 Eclipse （自动 import）一样自动增加配置？
* 应该反过来：检查有配置但是没有 require 的情况，甚至提供选项检查到没有 require 时自动删掉配置。

**Comment by sorrycc** [comment]
- 只有 import-style 和 handlebars-runtime 会自动加
- 没有 require 的包就算依赖了在构建时不会时也被包含进去，没啥影响的

**Comment by sorrycc** [comment]
案例：name 不符合规范。

http://spmjs.io/package/tipper
这个包的 name 大写，安装他之后 `spm doc` 就会出错。

**Comment by afc163** [comment]
http://spmjs.io/package/jsuri

同上的问题。

**Comment by afc163** [comment]
name publish 时的大小写校验的最好尽早搞掉。
