### ISSUE TITLE
standalone 支持 sourcemap

### ISSUE THREAD

**Issue by popomore** [spmjs/spm#1162]
CMD 模块支持 sourcemap 有 id 问题，但是 standalone 并没有问题，我觉得可以添加

**Comment by sorrycc** [comment]
standalone 现在是在 CMD 模块的基础上再进行的转化，加 sourcemap 要跳过 CMD 这一步吗?

**Comment by yiminghe** [comment]
+1

**Comment by yiminghe** [comment]
??x.js,y.js

combo 貌似会有问题

**Comment by popomore** [comment]
source 是 standalone 后的代码是不是可以？

**Comment by popomore** [comment]
CMD 一直有问题，感觉用 sourcemap 就是无解，所以才会有 seajs-debug

**Comment by hotoo** [comment]
+1 早上还想提这个需求来着

**Comment by sorrycc** [comment]
已支持。

**Comment by afc163** [comment]
combo 的确有问题。
