### ISSUE TITLE
spmignore 和 gitignore 问题

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#1167]
版本：spm@3.3.4

发布 arale-dialog 时发现，把 `spm_modules` 也发布到源上了。`spm_modules` 在 gitignore 中定义了，在 spmignore 中没定义，没有 npmignore 。

这个地方之前记得有改动，导致了这个问题？

**Comment by popomore** [comment]
是的，改成不是合并的关系，和 npm 逻辑保持一致

**Comment by afc163** [comment]
是有 .spmignore 就不读 .gitignore 的逻辑了？

**Comment by popomore** [comment]
是的

**Comment by afc163** [comment]
好。
