### ISSUE TITLE
spm standalone build moment@2.9.0 has bug

### ISSUE THREAD

**Issue by hotoo** [spmjs/spm#1168]
https://github.com/hotoo/spm-build-calendar

**Comment by sorrycc** [comment]
Fixed via cmdclean@0.2.10

**Comment by hotoo** [comment]
build 是好了，但是 spm-server 不知道为什么 output 没有加 seajs，报错 `Uncaught ReferenceError: define is not defined`

spm-server 没升级，好奇怪

```
$ spm-server -v
0.4.1
```

**Comment by hotoo** [comment]
重装了 spm-server 还是一样

**Comment by sorrycc** [comment]
把 tmp 目录删了试试。

**Comment by hotoo** [comment]
OK 了
