### ISSUE TITLE
spm 打包js目录问题，package如何配置

### ISSUE THREAD

**Issue by noonhorse** [spmjs/spm#1169]
环境：spm 3.3.2
package.json 的部分配置
<code > 
"source":"src",
    "output":  "**/main.js",
   "alias":[
  "zepto":"spm_modules/zepto/1.1.3/src/zepto"
],
"idleading": "{{version}}",
"dest": "dist",
 "buildArgs": "--include all"
</code>
目录结构
src ----temp
           &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;       ---main.js
   ----main.js
输出结果
dist/1.0.0/src
                 &nbsp;&nbsp; &nbsp;&nbsp;   ---temp
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; ---main.js /  main-debug.js
                  &nbsp;&nbsp; &nbsp;&nbsp;  ---- mian.js / mian-debug.js

为什么输出里面有src，如何去掉src

@sorrycc  @afc163  大神求解？谢谢

**Comment by sorrycc** [comment]
spm 的输出路径是和源码保持一致的，如果不想要 src，可以在源码里把 src  这层删掉。目前还不支持修改输出路径。

#1056 #1054

**Comment by afc163** [comment]
不要输出 src 目录里的文件就是了，在根目录直接放需要输出的文件。

另外 source alias dest idleading 这些应该属于 spm2 的配置，不适用于 spm3 .

**Comment by noonhorse** [comment]
我昨天和他们商量后的解决办法就是把src 的文件名改成 版本号 编译到dist下面去

**Comment by noonhorse** [comment]
@afc163 
根据 spm-build 的源码显示 ，idleading 和 dest 是保留的

![qq 20150122113134](https://cloud.githubusercontent.com/assets/4952447/5850122/69cd22a8-a22a-11e4-83ee-0ba96b062603.png)

https://github.com/spmjs/spm-build/blob/master/cli.js
你也可以看一下源码里还是有的
