### ISSUE TITLE
spm doc bug

### ISSUE THREAD

**Issue by yiminghe** [spmjs/spm#1171]
http://spmjs.io/docs/rc-calendar/examples/picker.html

线上出错
spm 3.3.2:  spm doc 是好的

但是 3.3.2 不能处理 md 里的

```
var zhCn = require('gregorian-calendar/lib/locale/zh-cn'); // spm error
```

请求路径没加版本号

**Comment by sorrycc** [comment]
服务器上临时修复了下，前面的例子可以跑了。

**Comment by afc163** [comment]
serve-spm 只是调试，standalone 是构建参数，两者因为什么有关联？

**Comment by sorrycc** [comment]
standalone 模式在使用时页面上是不载入 seajs 的，所以入口文件在调试时需要自动加入 seajs 并配置上 base 才能用。

**Comment by afc163** [comment]
调试时都可以使用 seajs 吧，这时候感觉没必要引入 standalone 的概念。

**Comment by sorrycc** [comment]
serve-spm 是基于真实使用场景进行处理的，生产环境上怎么使用就怎么调试。这样不同环境不需要切换，并且调试线上代码也比较方便。

**Comment by afc163** [comment]
但实际上 standalone 的构建参数并不是由当前模块决定的，是最终部署的模块来决定的，所有构建参数在线下调试阶段就是不确定的。而且 scripts 中的 buildArgs 里的参数也只是一个默认值，并非一定是实际使用的构建参数。

这里做了绑定反而增加了复杂度，建议还是彻底分开，我们需要保障的是`本地调试的使用效果和构建后的使用效果尽可能一致`就行了。

**Comment by sorrycc** [comment]
确实是增加了复杂度。不过如果不支持  standalone 的调试，使用起来会不太方便啊。

**Comment by afc163** [comment]
我担心所有的构建参数都要在 serve-spm 进行实现，这个有点不可控。

---

另外，根据 #1158 里提到的静态化，如果我们把本地调试的 `watch & serve` 彻底改为 `watch & build-debug`，是不是就可以把构建和调试放到同一个流程下了，这样逻辑只需要实现一份。

**Comment by sorrycc** [comment]
恩，静态化是应该这样处理。不过 build-debug 应该还是要经过 serve-spm 处理，所以还是会有两份实现吧。

**Comment by afc163** [comment]
可以直接 `require('spm-build')

**Comment by sorrycc** [comment]
spm-build 慢啊。而且如果是非 relative 模式的话，打出来的代码包含所有依赖，调试的时候会不方便吧。

不过貌似 browserify 和 duojs 都是这样做的。

**Comment by afc163** [comment]
就是简单打包吧，补齐 id 和依赖就完事，所以其实这里 standalone 也不应该去关注。速度的确是最关键的问题。

**Comment by sorrycc** [comment]
简单打包就是 serve-spm 现在做的事情啊。

**Comment by afc163** [comment]
现在是 serve 实时打包，并不是全打包。静态化需要全打包，文件一多的话，速度可能会悲剧。

**Comment by sorrycc** [comment]
静态化应该可以把全部文件通过 serve-spm 掉一遍，我试试。

**Comment by afc163** [comment]
无论是静态化还是现在的方案，调试还是忽略掉构建参数比较好。使用者不应该在调试时以后会用什么构建参数。

**Comment by sorrycc** [comment]
组件是不需要关心构建参数，但是项目的构建参数理论上就是他上线时的参数。

**Comment by afc163** [comment]
比如 chair 里的项目用的可能是自己的 build 脚本？

**Comment by sorrycc** [comment]
spm-server 是 spm-build 是配套的，他自己处理 build 的话，serve 也要自己处理啊。

不过这样说起来，感觉 serve-spm 可以处理地纯粹一点，standalone 这些逻辑可以放到 spm-server 里。

**Comment by afc163** [comment]
是的，spm-server 天生就是面对项目的，也能解决线上调试的问题。

**Comment by yiminghe** [comment]
hurry ...
````js
var zhCn = require('gregorian-calendar/lib/locale/zh-cn'); // spm error
````
请求路径没加版本号

还没解决啊

**Comment by sorrycc** [comment]
@yiminghe master 里修复了。

**Comment by yiminghe** [comment]
发个小版本？

**Comment by yiminghe** [comment]
又 bug 了  http://spmjs.io/docs/rc-form-validation/latest/examples/

@sorrycc

**Comment by sorrycc** [comment]
@yiminghe 好了。

**Comment by yiminghe** [comment]
@sorrycc 还是不行啊，要不静态化优先级高点，至少能稳定

**Comment by yiminghe** [comment]
强制清除缓存好了，坑啊
