### ISSUE TITLE
spm publish 强制覆盖

### ISSUE THREAD

**Issue by wenxian-liao** [spmjs/spm#1177]
没有一个类似之前spm2 publish -f 的强制覆盖命令吗？有时候会有这样的需求的。

**Comment by sorrycc** [comment]
#1001 spmjs/spmjs.io#86

强制覆盖的功能存在稳定性隐患，已删。如果有删包需求，可发 issue 或联系管理员。

**Comment by hotoo** [comment]
建议升级版本，并 unpublish 需要删的版本

**Comment by wenxian-liao** [comment]
新的版本 可以 unpublish 后，再 publish吗？可以覆盖相同版本号？
我的spm是 3.3.4，貌似是最高了呢

**Comment by afc163** [comment]
不能覆盖已发的版本，升版本。

**Comment by wenxian-liao** [comment]
@hotoo @afc163 明白了，刚把hotoo的理解错了

**Comment by shaoshuai0102** [comment]
publish -f 去掉是非常合理的，有利于生态模块的健壮与稳定
