### ISSUE TITLE
spm build --idleading 的一个bug

### ISSUE THREAD

**Issue by wenxian-liao** [spmjs/spm#1179]
package.json 配置
"buildArgs": "--dest _dist --ignore jquery --idleading app/1.0.1"
获得
define("app/1.0.1/app-debug", ["jquery","app/1.0.1/index-debug"], function(require, exports, module)

只要配置了idleading . import-style 就会出问题。
有没有办法跳过import-style，不解析 import-style，自行引入seajs-style.js，ignore skip测试不行。

**Comment by sorrycc** [comment]
idleading 只能支持 `{{name}}/{{version}}` 这种模板，然后值会从 package.json 里取。

不知道你的场景是啥。app/1.0.1 直接在 package.json 里配不就可以了吗? 为啥要写死?

**Comment by wenxian-liao** [comment]
@sorrycc 恩 解决了 --ignore import-style  .然后seajs 配置下 alias

**Comment by sorrycc** [comment]
不仅是 import-style，这样配 idleading 后所有依赖的 id 都会有问题。
