### ISSUE TITLE
standalone模式module['exports']解析错误

### ISSUE THREAD

**Issue by shaoshuai0102** [spmjs/spm#1180]
源码

![image](https://cloud.githubusercontent.com/assets/456108/5915695/ae1088f2-a643-11e4-971b-b40c29ceb737.png)

编译后：

![image](https://cloud.githubusercontent.com/assets/456108/5915702/b82e2ace-a643-11e4-8079-0aaa2058adab.png)

**Comment by afc163** [comment]
源码和编译后看着是一样的，贴错了？

**Comment by sorrycc** [comment]
编译后变成 `if (true)` 。cmdclean 没有处理 module['exports'] 只处理了 module.exports ，所以出错了。

**Comment by sorrycc** [comment]
Fixed via cmdclean@0.2.11，重装 spm 试试。

**Comment by shaoshuai0102** [comment]
tried

    npm install spm -g

but still not work

**Comment by sorrycc** [comment]
构建出来的代码还是之前的吗?

**Comment by shaoshuai0102** [comment]
是的



> 在 2015年1月27日，下午11:17，chencheng (云谦) <notifications@github.com> 写道：
> 
> 构建出来的代码还是之前的吗? 
>

**Comment by shaoshuai0102** [comment]
我搞错了，sorry

**Comment by afc163** [comment]
..
