### ISSUE TITLE
改进 standalone 模式的构建

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1181]
目前的 standalone 打包流程：

1. 分析 pkg
1. 为 commonjs 添加 cmd wrap
1. 分析 cmd 模块依赖关系
1. 调整模块顺序，cmd 代码去 cmd wrap

理论上中间两步是多余的，可直接根据 pkg 分析结构进行构建，性能上应该会有不少提升。

另外，现在的代码是基于 [amdclean](https://github.com/gfranko/amdclean) 修改而来，有时间可以考虑重构下。

**Comment by sorrycc** [comment]
standalone 模式下的 debug 文件输出不需要处理内部模块的 rename，所以可以放在一个流里来处理完。理论上可以减少一半的时间消耗。

**Comment by popomore** [comment]
我感觉都不需要添加 cmd wrap，直接对每个文件做 wrap 就可以了。

**Comment by sorrycc** [comment]
恩，是不需要。主题里列出的时现在的逻辑。

**Comment by wanderBee** [comment]
我还是用着不太明白：spm支持的是commonJs规范的，可是之前用CMD规范去适用Seajs的又咋整，难道seajs和spm放在一起用还不行吗

**Comment by popomore** [comment]
@wanderBee commonjs 是书写方式，其他的规范其实都是在浏览器执行时的，所以都是通过打包的。打包只要使用不同的工具就可以支持多种方案。

spm 在调试时其实也会动态转换成 CMD 的。

**Comment by wanderBee** [comment]
@popomore  spm打包：如果我的书写方式本来就是CMD的，需要弱化成 commonjs的吗？

**Comment by popomore** [comment]
spm2 是 CMD

**Comment by wanderBee** [comment]
@sorrycc 这样来看，中间2步就很有必要去掉了；不然，spm2和spm3对书写规范产生不同的要求了

**Comment by sorrycc** [comment]
@wanderBee 已经在 spm-webpack 中实现，详见：https://github.com/spmjs/spm-webpack/issues/2
