### ISSUE TITLE
新手请教一下怎么引入自己开发的插件呢？另外我压缩完后，只压缩了入口文件，可是我的引用的js模块都没有被压缩进来，是什么原因呢？

### ISSUE THREAD

**Issue by liuhaifeng2005** [spmjs/spm#1182]
请教一下怎么引入自己开发的插件呢？另外我压缩完后，只压缩入口文件，可是我的引用的js文件都没有被压缩，是什么原因呢？
package.json文件是这样的

```
{
  "name": "packgaename",
  "version": "1.2.3",
  "description": "miaoshuxinxi",
  "keywords": [],
  "homepage": "",
  "author": "liuhaifeng",
  "repository": {
    "type": "git",
    "url": ""
  },
  "bugs": {
    "url": ""
  },
  "licenses": "MIT",

  "spm": {
    "main": "src/index.js",
    "dependencies": {
      "seajs": "2.3.0",
	   "jquery": "1.8.3"
    },
    "devDependencies": {
      
    }
  },
  "devDependencies": {
    "spm": "3"
  },
  "scripts": {
    "test": "spm test",
    "build": "spm build"
  }

  
}
```

**Comment by afc163** [comment]
排版。。。

**Comment by liuhaifeng2005** [comment]
什么意思？

**Comment by afc163** [comment]
试试 `spm build --include all` 或 `spm build --include standalone`。

> 题主你不厚道。

**Comment by afc163** [comment]
http://spmjs.io/documentation/spm-commands#spm-build

**Comment by sorrycc** [comment]
syntax 是我加的。。:sweat_smile:

**Comment by liuhaifeng2005** [comment]
我再描述一遍，压缩是我用的是spm build命令，
index.html入口文件配置：
  seajs.config({
    base: "./"
  });
  seajs.use("src/index");
src目录下，是所有的js开发文件。现在只压缩了入口文件，其他的模块文件没有压进来。
2，我自己写的jquery插件怎么引进来呢？我用dependencies方式，老提示不成功！
3，开发的时候define需要添加吗？
刚开始看不太懂，求指教

**Comment by afc163** [comment]
先走一遍官方教程吧。http://spmjs.io/documentation/develop-a-package

或者看看 Arale 的文档：http://aralejs.org/docs/develop-components.html

**Comment by liuhaifeng2005** [comment]
文档看完了，没看明白，其他没问题了，怎么dependencies我自己开发的插件呢？
我这么写老报错。Not found. ~ http://spmjs.io/repository/util/src/util.js/
"dependencies": {
 "seajs": "2.3.0",
	   "jquery": "1.8.3",
     "util":"src/util.js"
    },

**Comment by liuhaifeng2005** [comment]
文档看完了，其他没问题了，就一个地方没搞明白，怎么dependencies我自己开发的插件呢？
我这么写老报错。Not found. ~ http://spmjs.io/repository/util/src/util.js/
"dependencies": {
"seajs": "2.3.0",
"jquery": "1.8.3",
"util":"src/util.js"
},

**Comment by alvin2ye** [comment]
1)
自己开发的控件也直接 publish 不就简单啦. 

2) 

在业务代码里 index.js
```
var XXX = require("./plugin/xxx");
```
