### ISSUE TITLE
build的时候，我的入口文件index.js，我require一个我写的模块，提示util is not in dependencies but required by index.js

### ISSUE THREAD

**Issue by liuhaifeng2005** [spmjs/spm#1187]
build的时候，我的入口文件index.js，require一个我写的模块，提示util is not in dependencies but required by index.js，是不是每一个模块读需要在package.json文件中做dependencies 呢？我写的几个模块文件都房子src中，如果每一个都需要dependencies ，那应该怎么设置呢，官网文档说明中都是
"dependencies": {
      "jquery": "1.8.3",
      "seajs": "2.3.0"
    },这种形式，这块我没看懂怎么处理，我自己写的怎么做dependencies 呢，求指教~

**Comment by sorrycc** [comment]
`require('./util')` require 本地相对文件用相对路径。

**Comment by liuhaifeng2005** [comment]
我用的是相对路径，刚刚我看文档说明，是需要上传到http://spmjs.io上吗？我的spm版本是3.3.4

**Comment by sorrycc** [comment]
写相对路径是不会出现前面的提示的。

**Comment by afc163** [comment]
引用模块内的其他文件使用相对路径。

引用其他模块使用绝对路径。

**Comment by lrn744809337** [comment]
@afc163  引用其他模块使用绝对路径 这个怎么理解，怎么写？

**Comment by afc163** [comment]
类似 npm 。

```
require('abc');        // 引用模块 abc 的入口文件
require('abc/file');  // 引用模块 abc 的 file.js 文件
require('./abc');      // 引用本模块内的 abc 文件
```

**Comment by lrn744809337** [comment]
@afc163 

像这样子呢：
-static
--test1
---dist
---index.js
--test2
---dist
---index.js

test1 引用test2

===============还有 
-lib
--abc
---abc.js
-static
--test1
---dist
---index.js
index.js 引用 abc.js

不考虑spm install 的话



------------------ Original ------------------

**Comment by afc163** [comment]
```
├── package.json
├── test1
│   └── index.js
└── test2
    └── index.js
```

放在同一个包内如何？

**Comment by lrn744809337** [comment]
@afc163  对第一个问题这样子应该ok的，
另外 ，一些非自己开发的lib，虽然已是闭包结构 ，但是 不能require
这个和 https://github.com/spmjs/spm/issues/821  描述的local功能是一样的吗
