### ISSUE TITLE
spm unpublish的疑问

### ISSUE THREAD

**Issue by lynzz** [spmjs/spm#1189]
我执行 spm unpublish xxx@1.0.0后

再执行 spm publish时，会提示  Cannot modify pre-existing version.

**Comment by afc163** [comment]
为了生态圈的稳定性考虑，3.3.0 时去掉了 unpublish 和 publish -f 。逻辑和 npm 保持一致。

https://github.com/spmjs/spm/issues/1046
https://github.com/spmjs/spm/issues/1177

**Comment by popomore** [comment]
unpublish 还有吧，只是不能重新 publish 相同版本了

**Comment by afc163** [comment]
@popomore 是，我修改了下。

**Comment by lynzz** [comment]
好的，明白了，谢谢
