### ISSUE TITLE
spm.main 兼容 browser 字段

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#1193]
https://github.com/muut/riotjs/blob/c1697feab1f0e1b72e5a87a30f44e817ffe6111b/package.json#L57

**Comment by sorrycc** [comment]
这是 npm 的标准?

**Comment by popomore** [comment]
貌似原来也不兼容 npm 吧？

这里加个 spm 不行？

**Comment by afc163** [comment]
加 spm 就没必要了。主要是 browser 字段和 spm.main 的含义应该是完全相同。和 main 就不一样了。

**Comment by sorrycc** [comment]
https://github.com/substack/browserify-handbook#browser-field
是 browserify 的规则

**Comment by sorrycc** [comment]
browser 字段有三种用途：

1. 指定 main
1. 文件替换，比如替换 a.js 为 a-browser.js
1. 忽略依赖包

**Comment by sorrycc** [comment]
例子：

https://github.com/visionmedia/superagent/blob/master/package.json#L47
https://github.com/cujojs/when/blob/master/package.json#L69

**Comment by afc163** [comment]
这么复杂，我以为就是个 main 。

基本上和 `spm` 字段的部分功能类似。

**Comment by afc163** [comment]
这么复杂兼容就算了，可以先参考参考里面的功能。
