### ISSUE TITLE
spm doc build生成的_site静态站点问题

### ISSUE THREAD

**Issue by zjgnlzq** [spmjs/spm#1195]
我想把spm doc build生成的_site当作一个长期运行的静态网站来跑，在原来的spm中有spm doc server，但是现在没有了！！求助。。。

**Comment by sorrycc** [comment]
`doc server` 还是有的啊，不过生成的 _site 目前还不是全静态的。#1158

**Comment by zjgnlzq** [comment]
我在组件根目录里运行spm doc server不行，看了一下spm-doc源码，里面确实没有，而其加-q参数直接退出了，浏览器里面看，服务没有启动。

##spm-doc文件片段
```
program
  .option('-r, --registry <url>', 'registry url of yuan server')
  .option('-p, --port <port>', 'local server port, default: 8000')
  .option('-f, --force', 'force build without cache')
  .option('-v, --verbose', 'show more logging')
  .option('-q, --quiet', 'show less logging')
  .option('--no-color', 'disable colorful print')
  .option('clean', 'clean _site folder')
  .option('build', 'build documentation')
  .option('watch', 'start a server of watching source')
  .option('publish', 'publish documentation for public');
```

**Comment by sorrycc** [comment]
想起来了，server 的功能去掉了。用 `spm doc` 吧，和 server 类似的。

**Comment by zjgnlzq** [comment]
用spm doc长期跑有问题：在linux上不好后台运行，我试过 ``` spm doc & ```能在当前bash中后台运行，但是日志都会打印出来，而其bash关闭后服务也自动关闭。  ```nohup spm doc >out.log 2>&1 &```这样服务根本无法运行。现在想到的临时办法是用screen，但是也不稳定。

另外请问一下，我是否可以把_site全部放到express的public目录中？

**Comment by sorrycc** [comment]
`doc server` 我加回来了。目前还不是全静态的，不能在 express 下直接运行。#1158

**Comment by zjgnlzq** [comment]
太好了！

**Comment by whuhacker** [comment]
@zjgnlzq 目前我用的是 `forever`，如果 `spm doc` 挂了会自动重启

**Comment by zjgnlzq** [comment]
```forever```也是在前台运行，如果你关闭当前shell，服务还是会停掉，而其spm doc对输出流重定向不了，我现在用```nohub spm doc server >log.txt 2>$1 $```，已经可以稳定运行了，而其性能还不错。

**Comment by whuhacker** [comment]
@zjgnlzq  没有啊，我一直用 forever，服务在后台没有停的。应该和 nohub 是类似的，只不过 forever 是用 nodejs 写的

**Comment by zjgnlzq** [comment]
@whuhacker 是的，谢谢你提供的方式。
