### ISSUE TITLE
spm install 命令是否能制定目标目录？

### ISSUE THREAD

**Issue by lvliujie** [spmjs/spm#1201]
如题，现在在用的spm install命令基本是在当前目录下创建一个spm_modules文件夹将代码全部放在里面，是否能通过配置某些参数直接加代码放入制定的文件夹下呢？

**Comment by sorrycc** [comment]
试试 `spm config install.path your_path` 。

**Comment by lvliujie** [comment]
使用了spm config set install.path my_path 可以配置了,但好像都是使用的相对路径,能使用绝对路径吗

**Comment by sorrycc** [comment]
目前不支持绝对路径。

**Comment by minuux** [comment]
修改spm依赖的spm-client模块的lib/install.js

在第46行
``` 
    args.destination = path.join(args.cwd, args.destination);
```
调整为
``` 
    args.destination = path.isAbsolute(args.destination)?args.destination:path.join(args.cwd, args.destination);
```

这样改完可以正常安装，但不知道是否有其它影响
