### ISSUE TITLE
支持 spm sync npm:xx

### ISSUE THREAD

**Issue by yiminghe** [spmjs/spm#1202]
递归批量更新/添加 npm 模块到 spm，功能和 tnpm sync xx 一样就可以额，这样能节省很多时间，还能减少出错。

**Comment by afc163** [comment]
可以在 https://github.com/sorrycc/ctos/ 基础上增加支持。

**Comment by sorrycc** [comment]
搞个单独的命令 `spm-sync` 吧，支持各种来源的包同步。

**Comment by afc163** [comment]
spm-transform

**Comment by yiminghe** [comment]
这个就不要 owner 概念了，任何人都可以 sync，最终达到 spm npm 同步，不同步的最好使用 domain 例如 @alipay/xx
