### ISSUE TITLE
spm build 中集成了 spm install 的问题

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#1207]
我印象中原来是没有的，在 spm3 以来，一直是贯彻构建和源交互隔离的原则。

这个 feature 不记得有 issue 讨论过，或者是我忘记了？

我的建议还是去掉，调试和构建前必须要进行 `spm install` 是合理的。

**Comment by popomore** [comment]
build 做的时候就增加这个功能了，为了方便吧。

**Comment by afc163** [comment]
只省一个命令意义不大啊。

**Comment by popomore** [comment]
为了安全吧，比如 package 里改了版本

**Comment by afc163** [comment]
那构建是不是就该报错？

**Comment by popomore** [comment]
语义化版本的话构建是不知道的。

**Comment by sorrycc** [comment]
有些场景是依赖 install 的：

- `import-style`, `handlebars-runtime` 需要动态 install
- `spm build entry.js` 时，会分析依赖列表并自动安装

**Comment by afc163** [comment]
>  import-style, handlebars-runtime 需要动态 install

理解了，这两个的确有一点潜规则。结贴。
