### ISSUE TITLE
spm doc试调环境 jquery引用路径存在问题

### ISSUE THREAD

**Issue by zjgnlzq** [spmjs/spm#1208]
## 问题重新步骤
1.执行命令
```bash
mkdir test
cd test
spm init
```
2.修改package.json
```
"dependencies": {
      "jquery": "1.10.1"
    }
```

3.修改index.js为
`` `
var test;

var $ = require('jquery')
console.log($().jquery)

module.exports = test;
```

4.运行 ```spm install & spm doc```后出现如下错误：
```
 GET http://static.alipayobjects.com/jquery//1.10.1/jquery.js 
index.js:6 Uncaught TypeError: object is not a function
```
经过分析发现是spm 自动设置的的paths： ```jquery: "http://static.alipayobjects.com/jquery/```存在问题

**Comment by afc163** [comment]
升级 spm 即可解决。
