### ISSUE TITLE
spm doc页面刷新问题

### ISSUE THREAD

**Issue by zjgnlzq** [spmjs/spm#1209]
在用spm doc试调组件时候，发现会出现代码修改后，命令行中有刷新显示，但刷新浏览器页面上还是老代码，进一步定位发现，这种情况是在浏览器控制的有js报错时候，刷新不了。

这个问题可以在[#issues 1208](https://github.com/spmjs/spm/issues/1208)看到，但jquery路径报错，修改index.md代码，不能自动刷新。

**Comment by sorrycc** [comment]
升级 spm 后还有问题?

**Comment by zjgnlzq** [comment]
3.4.1版本的spm依然存在这个问题

**Comment by sorrycc** [comment]
重现步骤? 和 #1208 的问题有啥区别?

**Comment by zjgnlzq** [comment]
和 [#1208](https://github.com/spmjs/spm/issues/1208)关联性不大，只是在[#1208](https://github.com/spmjs/spm/issues/1208)情况下也会出现

## 下面我写一个和[#1208](https://github.com/spmjs/spm/issues/1208)无关的，最简单的重现步骤：

1. 执行命令
```bash
mkdir test
cd test
spm init

spm install

spm doc
```

2.修改examples中的index.md文件
```javascript
var test = require('index');
console.log('test')
```
现在刷新浏览器可以看到新加的```console.log('test')```

3.修改examples中的index.md文件
```javascript
var test = require('index');
console.log('test'
```
这时候刷新浏览器，代码还是原来的```console.log('test')```，刷新不了。

**Comment by sorrycc** [comment]
按你说的步骤试了下，更新了啊。(mac + spm 3.4.1)

![image](https://cloud.githubusercontent.com/assets/35128/6407920/0cfca298-be85-11e4-99c0-44c5f52904d1.png)

**Comment by zjgnlzq** [comment]
我刚才又试了两遍，还是不能刷新，我的环境如下：
os: win7 64位
node: v0.10.35
spm: 3.4.1

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/6424722/4fd1f680-bf3f-11e4-8da6-7dafd15ccceb.png)

没 win7，试了下 winxp ，也是能刷新的。。奇怪了

**Comment by zjgnlzq** [comment]
是我自己机子的问题，现在已经恢复正常，谢谢
