### ISSUE TITLE
spm安装失败，求解~

### ISSUE THREAD

**Issue by yyzph** [spmjs/spm#1214]
C:\Users\Administrator>node -v
v0.12.0

C:\Users\Administrator>npm -v
2.5.1

C:\Users\Administrator>npm install spm@3.x -g
npm WARN deprecated 6to5@3.3.12: 6to5 is now 'babel': https://babeljs.io/blog/20
15/02/15/not-born-to-die
npm WARN deprecated 6to5@2.13.7: 6to5 is now 'babel': https://babeljs.io/blog/20
15/02/15/not-born-to-die
npm WARN deprecated 6to5-core@2.13.7: 6to5 is now 'babel': https://babeljs.io/bl
og/2015/02/15/not-born-to-die
npm WARN deprecated 6to5-core@3.6.5: 6to5 is now 'babel': https://babeljs.io/blo
g/2015/02/15/not-born-to-die
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the g
round up. Previous versions are no longer supported
-

> kexec@1.0.0 install C:\Program Files\nodejs\node_cache\node_modules\spm\node_m
odules\6to5\node_modules\kexec
> node-gyp configure build

\
C:\Program Files\nodejs\node_cache\node_modules\spm\node_modules\6to5\node_modul
es\kexec>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\
node_modules\node-gyp\bin\node-gyp.js" configure build
child_process: customFds option is deprecated, use stdio instead.
系统找不到指定的路径。
gyp: Call to 'node -v |grep "v0.11" > /dev/null && echo "__NODE_V0_11__" || echo
 "__NOT_NODE_V0_11__"' returned exit status 255. while trying to load binding.gy
p
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
 ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12
)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Program Files\nodejs\node_cache\node_modules\spm\node_modules\6t
o5\node_modules\kexec
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.5
npm WARN optional dep failed, continuing kexec@1.0.0
\

> phantomjs@1.9.15 install C:\Program Files\nodejs\node_cache\node_modules\spm\n
ode_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\ADMINI~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
.zip
Receiving...
| [====================================----] 91% 0.0s-
Received 7292K total.
Extracting zip contents
Removing C:\Program Files\nodejs\node_cache\node_modules\spm\node_modules\phanto
mjs\lib\phantom
Copying extracted folder C:\Users\ADMINI~1\AppData\Local\Temp\phantomjs\phantomj
s-1.9.8-windows.zip-extract-1425278922599\phantomjs-1.9.8-windows -> C:\Program
Files\nodejs\node_cache\node_modules\spm\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Program Files\nodejs\node_cache\node_modu
les\spm\node_modules\phantomjs\lib\phantom\phantomjs.exe
npm WARN optional dep failed, continuing fsevents@0.3.5

> kexec@1.1.0 install C:\Program Files\nodejs\node_cache\node_modules\spm\node_m
odules\spm-client\node_modules\6to5\node_modules\kexec
> pangyp configure build

'pangyp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm WARN optional dep failed, continuing kexec@1.1.0
C:\Program Files\nodejs\node_cache\spm -> C:\Program Files\nodejs\node_cache\nod
e_modules\spm\bin\spm

> spm@3.4.2 postinstall C:\Program Files\nodejs\node_cache\node_modules\spm
> node scripts/postinstall.js

[spm:preinstall] Phantomjs is installed in C:\Program Files\nodejs\node_cache\no
de_modules\spm\node_modules\phantomjs\lib\phantomjs.js
spm@3.4.2 C:\Program Files\nodejs\node_cache\node_modules\spm
├── inherits@1.0.0
├── crequire@1.5.3
├── internal-ip@1.0.0
├── co@3.1.0
├── empty-dir@0.1.0
├── win-spawn@2.0.0
├── spmrc@1.2.0
├── spm-log@0.1.2
├── extend@2.0.0
├── test-console@0.7.1
├── commander@2.5.1
├── archy@1.0.0
├── colorful@2.1.0
├── rimraf@2.2.8
├── semver@4.1.1
├── scripts-hook@0.1.3 (thunkify@2.1.2, co@4.1.0)
├── debug@2.1.2 (ms@0.7.0)
├── whoami@0.0.3 (shelljs@0.3.0)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.7)
├── fstream@1.0.4 (inherits@2.0.1, graceful-fs@3.0.5, mkdirp@0.5.0)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
├── exeq@2.0.2 (native-or-bluebird@1.1.2, bluebird@2.9.13)
├── fs-symlink@1.1.0 (mz@1.3.0, mkdirp-then@1.0.1, bluebird@2.9.13)
├── fs-extra@0.13.0 (jsonfile@2.0.0, ncp@1.0.1)
├── nico-spm@0.5.2 (commander@2.1.0, markit@0.1.0, underscore@1.5.2, swig@0.1
4.0, glob@3.2.11, highlight.js@7.5.0)
├── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, aws-sign2@0.5.
0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0
, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, bl@0.9.4,
http-signature@0.10.1, form-data@0.2.0, tough-cookie@0.12.1, hawk@1.1.1)
├── gulp-template@1.1.1 (through2@0.6.3, gulp-util@3.0.4, lodash@2.4.1)
├── vinyl-fs@0.3.13 (graceful-fs@3.0.5, strip-bom@1.0.0, vinyl@0.4.6, default
s@1.0.0, mkdirp@0.5.0, through2@0.6.3, glob-stream@3.1.18, glob-watcher@0.0.6)
├── father@0.11.0 (extend@1.3.0, arale@0.2.0, debug@1.0.4, mixarg@0.2.0, exis
ts-case@0.1.0, vinyl@0.4.6, semver@2.3.2, css-imports@0.3.1, glob@4.0.6)
├── gnode@0.1.1 (regenerator@0.8.15)
├── istanbul@0.3.6 (abbrev@1.0.5, supports-color@1.2.1, which@1.0.9, wordwrap
@0.0.2, once@1.3.1, nopt@3.0.1, async@0.9.0, mkdirp@0.5.0, resolve@0.7.4, filese
t@0.1.5, esprima@2.0.0, escodegen@1.3.3, handlebars@1.3.0, js-yaml@3.2.7)
├── react-tools@0.12.2 (jstransform@8.2.0, commoner@0.10.1)
├── 6to5@3.3.12 (fs-readdir-recursive@0.1.0, roadrunner@1.0.4, supports-color
@1.2.0, globals@5.1.0, js-tokenizer@1.3.3, private@0.1.6, commander@2.6.0, estra
verse@1.9.1, esutils@1.1.6, chalk@0.5.1, ast-types@0.6.15, output-file-sync@1.1.
0, acorn-6to5@0.11.1-25, detect-indent@3.0.0, source-map@0.1.43, chokidar@0.12.6
, source-map-support@0.2.9, core-js@0.4.10, regexpu@1.1.0, regenerator-6to5@0.8.
9-8, lodash@3.0.0, useragent@2.1.5)
├── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, throu
gh@2.3.6, readline2@0.1.1, chalk@0.5.1, lodash@2.4.1, cli-color@0.3.2, rx@2.4.1)

├── spm-build@1.3.0 (flatten@0.0.1, uniq@1.0.1, thunkify@2.1.2, co@4.1.0, uny
ield@0.0.1, step.js@2.0.5, mixarg@0.2.0, through2@0.6.3, cdeps@0.1.0, multipipe@
0.1.2, gulp-mirror@0.3.1, glob@4.3.5, gulp-if@1.2.5, gulp-minify-css@0.3.13, fat
her@0.13.1, gulp-uglify@1.0.2, spm-client@0.2.11, gulp-spm@0.11.1, gulp-zip@2.0.
3, gulp-size2@0.4.0, gulp-autoprefixer@2.1.0, gulp-6to5@2.0.2)
├── phantomjs@1.9.15 (which@1.0.9, progress@1.1.8, kew@0.4.0, request-progres
s@0.3.1, fs-extra@0.16.3, adm-zip@0.4.4, npmconf@2.0.9, request@2.42.0)
├── mocha-phantomjs@3.5.3 (commander@2.0.0, mocha@1.20.1)
├── spm-client@0.3.7 (co@4.1.0, co-request@0.2.0, minimist@1.1.0, mkdirp@0.5.
0, semver@4.2.2, multipipe@0.1.2, gulp-gunzip@0.0.2, gulp-untar2@0.0.6, father@0
.10.6, 6to5@2.13.7)
└── serve-spm@0.10.2 (searequire@1.5.3, gulp-reactify@1.0.3, strip-comments@0
.2.0, mime@1.2.11, generator-support@0.0.1, chalk@0.5.1, vinyl@0.4.6, rename@0.2
.3, css-imports@0.3.1, semver@3.0.1, through2@0.6.3, multipipe@0.1.2, gulp-if@1.
2.5, gulp-coffee@2.1.2, glob@4.0.6, handlebars@1.3.0, gulp-6to5@3.0.0, gulp-less
@1.3.9)

C:\Users\Administrator>spm -v
'spm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by sorrycc** [comment]
```
C:\Program Files\nodejs\node_cache\spm -> C:\Program Files\nodejs\node_cache\nod
e_modules\spm\bin\spm
```

看起来已经安装成功了，是不是 PATH 没配对?

**Comment by sorrycc** [comment]
试了下 winxp 下安装成功的。

**Comment by yyzph** [comment]
@sorrycc 需要怎么配PATH？有相关的文档吗？还有，是不是一定要装git

**Comment by yyzph** [comment]
@sorrycc 把环境变量改成 C:\Program Files\nodejs\node_cache\node_modules\spm\bin\spm 可以了
