### ISSUE TITLE
spm的一个小小建议

### ISSUE THREAD

**Issue by zjgnlzq** [spmjs/spm#1216]
###  为了spm能够更好更快的在国内开发者中推广，建议spm新版本发布前，在win7上做一下安装、使用等方面的测试。

**Comment by popomore** [comment]
多谢，我们会多关注这方面的进展，也谢谢推荐 spm。

**Comment by afc163** [comment]
感谢你的反馈，npm 模块对于 window 的兼容一直是一个坑，我们也的确收到了很多这方面的安装问题。由于 windows 本身版本繁多在安装测试上难以面面俱到。我们也希望使用 windows 的朋友像楼主一样能持续帮助我们改进这个问题，如果遇到问题可以：

1. 使用 google 和 [npm 上大量关于 windows 的 issues](https://github.com/npm/npm/labels/windows) 排查问题，很多问题是依赖模块的兼容性造成的。
2. 及时反馈，我们会尽快处理。
3. 事后可以将安装时候遇到的坑整理分享出来，帮助其他同学。

再次感谢楼主。

**Comment by zjgnlzq** [comment]
不客气，我也是seajs社区的一员，从中收获颇多，大部分时候还是在享受seajs、spm带来的好处。感谢你们的付出给大家带来很多好的东西。希望seajs生态圈发展越来越好。
