### ISSUE TITLE
spm3@3.4.2 这个版本在build的时候会出现process out of memory

### ISSUE THREAD

**Issue by peng2e** [spmjs/spm#1217]
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
git 线上地址： https://github.com/acharts/acharts  当下来后执行spm3 build。 会报错 https://github.com/acharts/acharts ， 版本回滚到3.4.0 搞定。谢谢 @云谦 
环境：  window 7 64bit

**Comment by sorrycc** [comment]
https://github.com/spmjs/gulp-spm/pull/30
和这个问题相关。
