### ISSUE TITLE
spmjs.io 搜索坏了

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1221]
![image](https://cloud.githubusercontent.com/assets/5401/6590479/a5c97a7c-c7eb-11e4-9e8a-0e7547f34d2f.png)

**Comment by afc163** [comment]
Fixed.

**Comment by sorrycc** [comment]
http://bobao.360.cn/news/detail/1273.html
elasticsearch 又出漏洞了。。要升级到 1.4.3
