### ISSUE TITLE
react 通过 standalone 打包出这个错误

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1223]
![image](https://cloud.githubusercontent.com/assets/5401/6632582/b4e63476-c973-11e4-9e96-6dfcd083757d.png)

压缩包

http://agi-public3.qiniudn.com/20150313112648/spm-react.tar.gz

**Comment by sorrycc** [comment]
react 打包有问题，目前我们是这样处理的。

1. react 单独载入
1. 打包的时候配置 `"buildArgs": "--global react:React"`

**Comment by alvin2ye** [comment]
👌 

用all 打包正常
