### ISSUE TITLE
用户名的大小写差异导致无法publish

### ISSUE THREAD

**Issue by nimojs** [spmjs/spm#1225]
请先看如下两个链接
http://spmjs.io/account/NimoJs  显示 packages(1)
http://spmjs.io/account/nimojs  显示 packages(0)

NimoJs 是我以前github的账号，并publish 了 nodeajax，后来将github用户名的 `N` 和 `J` 修改为了 `n` `j`。 

现在我发现我无法使用 nimojs publish 内容了，我确定我没有复制错 Authkey

我估计是因为用户名大小写导致的错误。
```
// spm v:3.4.2 
// Mac v: 10.10
viewlist $spm publish

        publish: viewlist@0.0.0
         target: http://spmjs.io
           exit: authorization is required. try `spm login`

viewlist $spm login

? username (your github account username):  nimojs
? authkey (copy from spmjs account page):  ********************************

  login success.

viewlist $spm publish

        publish: viewlist@0.0.0
         target: http://spmjs.io
           exit: authorization is required. try `spm login`

viewlist $spm login
```

**Comment by afc163** [comment]
是这个问题。https://github.com/spmjs/spmjs.io/issues/101

**Comment by nimojs** [comment]
感谢回复。希望告知何时解决此 BUG，或有什么临时解决方案？

**Comment by afc163** [comment]
着急吗，等周一了我来看看？

**Comment by nimojs** [comment]
不是特别急，但是后续是需要 publish 和更新 Nimojs 这个旧账号的package。
:smile:  麻烦偏右了~

**Comment by afc163** [comment]
问题不是很好解决，暂时先把原来仓库的权限改到 http://spmjs.io/account/nimojs 下了。这里先关了，到 https://github.com/spmjs/spmjs.io/issues/101 下继续跟踪。
