### ISSUE TITLE
请教关于SPM3的实践

### ISSUE THREAD

**Issue by nimojs** [spmjs/spm#1227]
我使用 seajs 作为模块加载器，
搭建了前端静态资源服务器 (安装了nginx-http-concat)
现有目录如下
```
- spm/
- spm_modules/
```

spm 由 spm_modules 下对应模块构建而成 

```
$ cd spm_modules/arale-upload/1.2.0/
$ spm build -O ../../../spm
```
使用此方式构建后， `spm/` 目录下文件就都是 CMD 模块文件。

在页面中使用 seajs 加载模块
```
<script src="/spm/??seajs/2.3.0/sea.js,seajs-combo/1.0.1/seajs-combo.js"></script>
<script>
seajs.config({
    base: '/spm/',
    alias:{
        'jquery': 'jquery/1.11.2/jquery'
    }
})
seajs.use(['jquery','arale-upload/1.2.0/index'], function ($,Uploader) {
    console.log($)
    console.log(Uploader)
})
```

**请教：**  
1. 使用此方式我需要将每个所需模块都执行一次  `spm build -O ../../../spm` 是否有快捷方法可以一次性将 `spm_modules/` 所有文件全部 build ？
2. 利用服务器做自动 combo 来减少本地打包的操作有什么坏处？

**Comment by afc163** [comment]
>  2. 利用服务器做自动 combo 来减少本地打包的操作有什么坏处？

支付宝主站就是一直使用的这种方式，缺点是需要提前把模块、模块的依赖链的所有模块都提前发布到线上。所以我们推荐使用 standalone 的方式。

**Comment by afc163** [comment]
> 使用此方式我需要将每个所需模块都执行一次  `spm build -O ../../../spm` 是否有快捷方法可以一次性将 `spm_modules/` 所有文件全部 build ？

目前可以使用 `spm build --with-deps` 来打包依赖模块，同样会输出到 dist 目录中。

**Comment by nimojs** [comment]
@afc163 
`spm build --with-deps` 太好用了，十分感谢。

我打算预先 build 常用模块发布线上，然后用服务器 combo 的方式让前端新人在不熟悉 spm 的情况下也可以创造生产力。

**再请教一个问题：**

支付宝团队是如何解决本地模拟线上 combo 的?

因为 combo 的原因，不能简单的使用 charles 或 fiddler 进行 host rewrite，
我在本地用 node listen(1111)，combo  本地的 spm 资源。`http://127.0.0.1:1111`。

本地配置 base 
```
seajs.config({
    base: 'http://127.0.0.1:1111/spm/'
})
```

线上 `base: 'http://cdn.domain.com/spm/'`

前端本地开发环境和线上后端环境中 base 地址通过后端模板引擎控制

```
seajs.config({
    base: '{{STATIC_DOMAIN}}/spm/'
})
```


**请教**：
此方式依赖于前端本地开发环境和后端框架的支持，有没有什么方法可以 “0” 成本的模拟 combo？

支付宝的前端离线开发环境是如何模拟 combe ？

**Comment by alvin2ye** [comment]
@nimojs 不考虑用 include all 吗?

**Comment by nimojs** [comment]
@alvin2ye SPA等考虑 standalone
一般情况将常用模块部署到前端cdn服务器。这样只关注编码，不手动构建。

**Comment by afc163** [comment]
@nimojs 可以看看 https://github.com/popomore/connect-combo

**Comment by nimojs** [comment]
@afc163  太好了，感谢。大厂果然什么都全

**Comment by sorrycc** [comment]
https://github.com/spmjs/spm-server
调试可以用 spm-server，内置了 combo 的解析的。

**Comment by nimojs** [comment]
@sorrycc 感谢云谦
