### ISSUE TITLE
spm在js引入css 的问题, 在handbook 看到这段, 并且写了DEMO没用, 是过时了吗?

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1228]
![image](https://cloud.githubusercontent.com/assets/5401/6671649/b766d43c-cc41-11e4-9f67-120dd300e45c.png)

**Comment by sorrycc** [comment]
是 `require('alice-box');`，文档写错了。

**Comment by alvin2ye** [comment]
恩, 后来自己使出来了.

还有,我觉得这里要提醒一下用户 开发模式下要先引用  seajs-style

**Comment by afc163** [comment]
修正一下吧，这里提过多次了。@sorrycc

**Comment by hotoo** [comment]
不是 @import 么？

**Comment by sorrycc** [comment]
改了，但 gitbook.io 编译出错，且没提示具体原因。。我再找时间把文档都迁移回 spm 的服务器。

**Comment by sorrycc** [comment]
https://github.com/spmjs/docs
文档以这个为准。
