### ISSUE TITLE
spm3  spm-init 的模板现是不支持配置？

### ISSUE THREAD

**Issue by lynzz** [spmjs/spm#1229]
因有自定义  spm-init 初始模板的需求，看了 spm-init  源码有这么一段 log

Change init default template in ~/.spm/spmrc-3x

但没看到有从 spmrc 获取模板

**Comment by sorrycc** [comment]
感谢反馈。是不支持配置，我把那段帮助信息删了。自定义脚手架的需求可以通过 `yeoman` 实现。

**Comment by lynzz** [comment]
嗯 当算用 yeoman 来实现
