### ISSUE TITLE
spm运行测试文件时js文件路径错误

### ISSUE THREAD

**Issue by yunfour** [spmjs/spm#1230]
使用spm doc命令运行服务后，在浏览器中运行中访问自动化测试页面http://127.0.0.1:8000/tests/runner.html时，控制台报错，说一个JS路径错误：Failed to load resource: the server responded with a status of 404 (Not Found) http://127.0.0.1:8000/E:/frontendCase/epay-modules/epay-event/tests/index-spec.js，我看了一下，是把index-spec.js文件的路径给搞错了，把本地绝对路径前有添加了服务器host，请问这是哪个文件配置出错了

**Comment by sorrycc** [comment]
#1218，升级到 3.4.3 试试。
