### ISSUE TITLE
不需要build require('source-map') 代码块

### ISSUE THREAD

**Issue by nimojs** [spmjs/spm#1233]
`spm build` cmd 模块时，会获取 `require('name')` 信息并加入头部 `define(id,deps)` 的deps 中。

我按照[迁移业界优秀模块到 spmjs.io 并反推的简易教程](https://github.com/spmjs/spm/wiki/%E8%BF%81%E7%A7%BB%E4%B8%9A%E7%95%8C%E4%BC%98%E7%A7%80%E6%A8%A1%E5%9D%97%E5%88%B0-spmjs.io-%E5%B9%B6%E5%8F%8D%E6%8E%A8%E7%9A%84%E7%AE%80%E6%98%93%E6%95%99%E7%A8%8B) 将 handlebars 3.0.0 迁移至 spm 时发现 handlebars 中包含如下代码块。

```
try {
    var SourceMap = require('source-map'),
          SourceNode = SourceMap.SourceNode;
  } catch (err) {
```

我理解这里的是在支持 require 的情况下才使用 require。但 `spm build`的结果是

```
define("handlebars/3.0.0/dist/handlebars", ["source-map/1.0.2/source-map"]
```

遇到这种情况应该如何处理？

ps: 我发现 handlebars 的 cjs 版本依赖了很多模块，而这些模块在 spm上暂时没有。所以我直接对 `dist/handlebars.js` 进行构建。这样迁移模块可以么？

**Comment by popomore** [comment]
用 skip

**Comment by nimojs** [comment]
```
$ spm build -O ../../spm -skip source-map
```
报错：
```
 error: unknown option `-k'
```

**Comment by afc163** [comment]
--skip

**Comment by nimojs** [comment]
我太粗心。可以了，感谢。

**Comment by nimojs** [comment]
感谢二位指点，已将 handlebars 改造成 spm 模块。
@popomore @afc163 

我没有权限 publish ，希望二位抽空 publish。文件在此处 https://github.com/nimojs/demo/tree/gh-pages/package/spm 我删除了cjs 和 amd 文件，只保留了构建所需文件和文档。

**Comment by popomore** [comment]
https://github.com/spmjs/handlebars.js

**Comment by nimojs** [comment]
收到~
