### ISSUE TITLE
standalone 方式如何提高本地开发效率

### ISSUE THREAD

**Issue by hub0111** [spmjs/spm#1234]
我现在使用 standalone 方式打包文件，但每次修改commonjs 版本的源码后都需要build 。有没有什么方法可以修改commonjs版本后"瞬间 build" ??

**Comment by hotoo** [comment]
https://github.com/spmjs/spm-server

**Comment by hub0111** [comment]
不好意思，我只看到了livereload  、weinre 和代理。
如何利用spm-server 自动构建 standalone ？

**Comment by afc163** [comment]
https://github.com/spmjs/spm/wiki/%E8%B0%83%E8%AF%95-CommonJS-%E6%BA%90%E7%A0%81

**Comment by afc163** [comment]
https://github.com/spmjs/spm-server/issues/7
