### ISSUE TITLE
讨论：spm-server 和 spm doc 改成基于编译的方式

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1236]
优点：

1. 稳定 (现在和构建是分开处理的，存在调试通过但构建不通过的问题)
1. 降低维护成本 (将不需要再维护 serve-spm)
1. doc 全静态化

潜在问题：

1. 耗时长问题 (webpack 的 watch 模式可以增量编译，已无性能问题)
1. 构建后的文件和源码的一一对应问题 (通过 sourcemap 解决)
1. seajs 模式的项目 (没想到啥好的方案，依旧使用 serve-spm)

**Comment by afc163** [comment]
spm doc 主要解决的是直接调试源码的问题，这样在开发过程中非常方便。

编译的话如果要花比较长的时间，会大大影响体验。

**Comment by sorrycc** [comment]
编译耗时问题可以忽略了，webpack 的编译是增量的，修改某个文件后只会对那个文件，很快。

**Comment by sorrycc** [comment]
不过和 nico 的整合可能还会有些坑，等开始做的时候再仔细想想。

**Comment by afc163** [comment]
速度够快的话其实就没啥区别了，watchify 现在就是这么做的。

**Comment by hotoo** [comment]
seajs 模式下，是否可以考虑通过设置 base 到编译目录的方式？

**Comment by hotoo** [comment]
spm doc watch 模式，还需要保留 socket 服务，提供 liveload 特性吧。

**Comment by sorrycc** [comment]
@hotoo 

- seajs 模式不能走 webpack，所以不能走这个流程 (编译慢)
- 不会影响 livereload 功能的

**Comment by sorrycc** [comment]
![](https://t.alipayobjects.com/images/T1U2dfXbBvXXXXXXXX.png)
上个图。如果不考虑 seajs 的方案，这样改了之后，调试和文档都基于构建实现，那么 spm 本身会变得非常简单。

**Comment by afc163** [comment]
发布包不应该依赖构建吧，只有文档的发布需要依赖。

**Comment by sorrycc** [comment]
不依赖，从下往上依赖。。难道我箭头的含义画反了?

**Comment by sorrycc** [comment]
另外，文档性能应该也能提升。依赖的 js 文件从很多请求变成一个请求了。

**Comment by army8735** [comment]
能自定义插件开发吗

**Comment by sorrycc** [comment]
@army8735 啥插件? 构建时的吗?

**Comment by yiminghe** [comment]
webpack devserver middleware 支持内存构建，快

**Comment by sorrycc** [comment]
https://github.com/spmjs/spm-webpack-server
server 已完成，包含原有 spm-server 的所有调试功能。

**Comment by yiminghe** [comment]
怎么支持 coverage 文件

**Comment by wanderBee** [comment]
之前的spm-server也是cmd wrap，用seajs管理的；现在的增强鼓励大家搁置seajs。。。

**Comment by sorrycc** [comment]
已完成。
