### ISSUE TITLE
spm doc watch 的页面模板本身的兼容性问题

### ISSUE THREAD

**Issue by hotoo** [spmjs/spm#1237]
比如在 IE 8 中，由于模板页面本身的异常，影响了排查模块的兼容性问题。

不说 UI 的兼容性，模板请至少不要抛出 JavaScript 异常。

![2015-03-24 11 44 28](https://cloud.githubusercontent.com/assets/143572/6795492/7adb4662-d21b-11e4-8dbc-122f06017854.png)

**Comment by afc163** [comment]
这个是二维码的显示问题，应该不影响 demo 的展示和使用。
