### ISSUE TITLE
spm 如何和gulp集成起来用

### ISSUE THREAD

**Issue by elover** [spmjs/spm#1238]
由于项目里有些需要自定义的东西，所以需要考虑集成gulp使用，想问一下目前有没有好的办法？

**Comment by elover** [comment]
之前用spm2的时候，就是用了grunt的两个插件来使用的，请问到了spm3时代，是否还有类似工具可以用呢，试了一下gulp-spm发现不会用了

**Comment by afc163** [comment]
可以看看 https://github.com/spmjs/gulp-spm/blob/master/test/transport.test.js

**Comment by elover** [comment]
你们可不可以分享一下，自己公司的打包方式，不应该只是基于spm的命令行吧？

**Comment by afc163** [comment]
是，基本上就是 `spm build` 或者 `spm build --standalone`。

最近 @sorrycc 在进行构建底层的替换，将升级到基于 webpack 的打包方式，可以关注一下。https://github.com/spmjs/spm-webpack

**Comment by elover** [comment]
多谢，spm很多东西发展很快，不仅文档跟不上，关键的是连example也很难找到，建议源码里面增加example这个目录吧

**Comment by afc163** [comment]
https://github.com/spmjs/examples

**Comment by sorrycc** [comment]
更新下：

- 例子：https://github.com/spmjs/examples/tree/spm-webpack
- 文档：https://github.com/spmjs/docs
