### ISSUE TITLE
 opt.dest  could be customized by user

### ISSUE THREAD

**Issue by majorye** [spmjs/spm#1239]
现在 spm build的dist是  dist/opt.idleading/opt.pkg ，但有的时候， 希望dist能够自定义，比如
只希望 dist就可以。 希望能够增加自定义参数.

**Comment by sorrycc** [comment]
不配 `name` 和 `version` 就不会生成这两级路径了。

**Comment by majorye** [comment]
@sorrycc  name和version 还是要的 ，大概说下情况, 目前使用的是gitlab发布，所以name和version目录，发布的时候，会自动生成好，只会发布dist下的文件，但如果按照目前的策略，就多了两层目录name/version , 希望能够用户自动以，不同的发布机制，方式不一样

**Comment by sorrycc** [comment]
我说的是 `package.json` 里的 name 和 version，gitlab 也都这两个吗?
