### ISSUE TITLE
spm报错undefined:1, Syntax: unexpected token

### ISSUE THREAD

**Issue by loveLibra** [spmjs/spm#1241]
如上，spm 重新安装过，运行的目录页是新建的，spm init报上述错误...在原来正常的目录下spm build 也是一样的错误，请问啥原因啊

**Comment by sorrycc** [comment]
出错信息给多点看看

**Comment by loveLibra** [comment]
完整的就是：
undefined:1
^
Syntax: unexpected token

所以很纳闷呢

**Comment by afc163** [comment]
给个能重现的包看看。

**Comment by loveLibra** [comment]
@sorrycc @afc163  估计还是版本的问题 包没啦 被干掉重新安装了 指定2.x版本 又好了...飘忽不定（话说不是我的机器，没留住现场~~）
