### ISSUE TITLE
spm 安装时报错

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#1242]
```
spm install rc-calendar --save
```

```
...
exit: no matched package react ~ *
```

**Comment by afc163** [comment]
而且不会安装依赖。

`spm@3.4.3`

**Comment by sorrycc** [comment]
spm@3.4.3 里已修复。
https://github.com/spmjs/spm/blob/master/HISTORY.md#343

**Comment by afc163** [comment]
嗯，报错的问题修复了，`3.4.3` 依赖没有安装。

**Comment by sorrycc** [comment]
依赖没有安装具体是啥?

**Comment by afc163** [comment]
`rc-calendar` 的依赖没有安装到本地。

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/6889590/fc200cd0-d6cb-11e4-8882-87e4d9186c3c.png)
试过没有问题啊

**Comment by afc163** [comment]
`rm -rf spm_modules` 后重新安装好了。
