### ISSUE TITLE
Spm build 自动给每个js 模块 加 define 函数的问题

### ISSUE THREAD

**Issue by yqfang** [spmjs/spm#1246]
开发的过程中 使用seajs 加载 模块, 所以 每个js 模块已经 使用: 

```
define(function(require, exports, module) {
	"use strict";
    .....
});
```

这种方式去做了, 现在 我用 spm 的 build 功能, 比如我要压缩我所有的seajs 模块代码(入口为app.js):

```
spm build app.js --include relative 
```

压缩美柚问题, 只是spm build 自动给每个js 模块又套了一层 define 函数(此时有两层define), 导致压缩的代码无法运行, spm build 之前 手动去掉 define 函数 再build 就没问题

我想知道, spm 这么做(自动 加 define) 的原因, 有没有什么办法可以控制这种行为?

**Comment by hotoo** [comment]
你这种情况请使用  spm@2.x 版本，使用 CMD 规范书写源码。
spm@3.x 版本遵循 CommonJS 规范，不需要写 define 包头尾，打包时会自动包 define。

**Comment by afc163** [comment]
https://github.com/seajs/seajs/issues/1459
