### ISSUE TITLE
spm构建require问题和去掉define问题

### ISSUE THREAD

**Issue by kongjiea** [spmjs/spm#1250]
1、环境如： define包裹中require('./a') ，不是说构建的时候尽量忽略避免然让requrie压缩替换么？可是用spm自动构建的时候却发现require关键字被替换了 如构建后

```
define("test/2.0.0/js/a", [], function(e, t, n) {
    function o() {
        var e = document.getElementById("box2");
        e.style.background = "#f60"
    }
    e("test/2.0.0/js/b"), n.exports = o
})
```

require 被替换成了e ，所以到底require能不能被替换掉？

2、package.json--buildArgs--include 默认是relative 可是我把设置成了 all为什么还报错呢?
报错内容  b is not in dependencies but required by js\a.js:

我的代码
配置如下

```html
<script>
        seajs.config({
            base: "../spm/",
            alias:{
                "a":'js/a',
                "b":'js/b'
            }
        });
</script>
```

a.js代码：

```
define(function(require,exports,module){
    require('b');
    function a(){
        var obj=document.getElementById('box2');
        obj.style.background="#f60";
    }
    module.exports=a;
})
```

package.json代码：

```
{
  "name": "test",
  "version": "3.0.0",
  "description": "demo spm",
  "author": "zuozhe",
  "license": "MIT",
  "spm": {
    "main": "js/a.js"
  },
  "buildArgs":{
    "include":"all"
  }
}
```

如上设置include为all为啥还是报错
报错内容  b is not in dependencies but required by js\a.js:

3、构建时候 去掉js中包裹的define
如a.js在构建的时候
```
define(function(require,exports,module){
    require('b');
    function a(){
        var obj=document.getElementById('box2');
        obj.style.background="#f60";
    }
    module.exports=a;
}) 
```
改成以下代码
```
    require('b');
    function a(){
        var obj=document.getElementById('box2');
        obj.style.background="#f60";
    }
    module.exports=a;
```
那假如我一个页面引入的是多个js 那不是很多js都要手动删除包裹的define岂不是很麻烦，因为构建完出错了，我可能还要还原测试... 感觉好麻烦啊

**Comment by elover** [comment]
你可以试一试gulp-cmd这个gulp插件来构建

**Comment by sorrycc** [comment]
1. 匿名 define 时不能替换  require 关键字，而 id 和 依赖写全的情况下是可以替换的
2. 没看到 package.json 里看到有 b 的依赖，所以你 require('b') 肯定会报错
3. 开发时用 commonjs，define wrap 是在构建时加入的，为啥要手动删?

**Comment by kongjiea** [comment]
@sorrycc  
那么我第二问题在package.json中要怎么制定依赖呢？是如下吗？
package.json代码：

{
"name": "test",
"version": "3.0.0",
"description": "demo spm",
"author": "zuozhe",
"license": "MIT",
"spm": {
    "main": "js/a.js",
    "dependencies": {
      "b": "", //貌似这里还要填写版本号 没看懂
    }
},
"buildArgs":{
"include":"all"
}
}

第三个问题追问：
因为在开发的时候我用的seajs，书写的时候就是遵循cmd规范，自然是本身就有define包裹，那么在用spm构建的时候 ，不是又要删除define 让spm自动添加最外层的define？？？

**Comment by afc163** [comment]
https://github.com/spmjs/spm/wiki/%E8%B0%83%E8%AF%95-CommonJS-%E6%BA%90%E7%A0%81

**Comment by kongjiea** [comment]
@afc163 更加看不懂了

**Comment by afc163** [comment]
建议按照官方文档走一遍：http://spmjs.io/documentation/develop-a-package

都按 CommonJS 来书写模块，就是类似 node 的方式。

不要用 CMD 了，甚至不要用 Sea.js 了。

**Comment by sorrycc** [comment]
https://github.com/spmjs/docs/blob/master/project/get-started.md
开发项目的话，按这个文档走一遍试试。有问题再新开 issue 吧。
