### ISSUE TITLE
有些大的包就是是开发模式下(spm-server) 也不想每次都加载所有子文件要怎么操作

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1252]
是不是只要配置下就行. 

![image](https://cloud.githubusercontent.com/assets/5401/7021652/8d39089e-dd56-11e4-849e-cb11102f8ce4.png)

**Comment by sorrycc** [comment]
配 global，比如 `--global react:React`，然后 react 通过 `<script>` 直接引入。

**Comment by sorrycc** [comment]
spm 3.6 的 server 基于 build 实现，不会再有此问题了。

**Comment by alvin2ye** [comment]
+1
