### ISSUE TITLE
不能使用邮箱登录

### ISSUE THREAD

**Issue by YuhangGe** [spmjs/spm#1253]
很小的issue啦，当前登录只能用用户名，如果能用邮箱登录就更好了。（折腾了5分钟才总算spm login成功了）

**Comment by sorrycc** [comment]
试了下，可以啊。

**Comment by YuhangGe** [comment]
我这边不行。使用abeyuhang@gmail.com登录失败，YuhangGe登录成功。

**Comment by afc163** [comment]
> Your primary GitHub email address will be used for account-related notifications (e.g. account changes and billing receipts) as well as any web-based GitHub operations (e.g. edits and merges).

是否是 `primary GitHub email address`

**Comment by YuhangGe** [comment]
对哦！很可能是这个问题。那可以把issue关掉了。建议在文档里login部分说明下~~

**Comment by YuhangGe** [comment]
不对，我刚才查了下，我的这个就是primary email...

**Comment by sorrycc** [comment]
应该是 github 的问题?

**Comment by YuhangGe** [comment]
如果没有其它同学报issue，应该就是特例了。我先把issue给close。
