### ISSUE TITLE
文件夹不为空时即使没有package.json仍然不能spm init

### ISSUE THREAD

**Issue by YuhangGe** [spmjs/spm#1254]
文件夹下面不为空，但没有package.json文件，仍然提示spm init只能在空文件夹下执行。

**Comment by afc163** [comment]
是的，建议新建文件夹。

**Comment by YuhangGe** [comment]
但用npm init就可以。不知道spm是出于什么样的考虑。有时候先写点代码，再想包装下publish。

**Comment by sorrycc** [comment]
npm init 只创建 package.json，spm init 是一个脚手架，包含文档、测试等。

**Comment by YuhangGe** [comment]
但spm init如果能做npm init的事，我就可以完全不使用npm啦。刚才就是发现不行，又先用npm init，然后再手动添加spm部分，稍微有些忧伤。否则的话，我就得去新建文件夹，然后spm init然后再把文件拷贝过去。

**Comment by sorrycc** [comment]
加个参数只生成 package.json 吧，我用的时候也遇到过这个问题。
