### ISSUE TITLE
自动build

### ISSUE THREAD

**Issue by itangpin** [spmjs/spm#1255]
开发浏览器js的时候，要想测试效果必须先build才可以用，有没有 --watch这样的用法，文件一有变动就自动build？
如果没有的话，未来会有吗，有没有什么实现同样效果的方式？

**Comment by afc163** [comment]
一般来说，测试阶段可以直接调试源码，不需要 build 。

https://github.com/spmjs/spm/wiki/%E8%B0%83%E8%AF%95-CommonJS-%E6%BA%90%E7%A0%81

**Comment by sorrycc** [comment]
spm@ninja 这个版本中已经可以用 `spm build --watch` 了。
