### ISSUE TITLE
spm@3.6 发布

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1258]
大家好，

这个版本的性能、稳定性均有显著提升。而由于改动比较大，所以跳了一个版本，直接发 3.6 。

![](https://t.alipayobjects.com/images/T1x5RfXi4nXXXXXXXX.png)

主要有以下改动：

**(1) 基于 webpack 重新实现了 build**

- 性能更快：比如钉钉的项目从之前的 `200s` 缩短到 `52s`，经过配置后最后到 `38s`
- 功能更强大：比如公用包和文件的提取，动态依赖、循环引用、node 模块补丁等，详见 [配置项](https://github.com/spmjs/docs/blob/master/zh-cn/project/configuration.md) 和 [案例](https://github.com/spmjs/examples/tree/spm-webpack)
- 扩展性更好：比如这样配置 `"loader": {".js":"+./foo"}`，即可对所有 js 文件用本地的 `foo.js` 进行额外处理，[Demo](https://github.com/spmjs/examples/tree/spm-webpack/custom-loader)

**(2) doc, server 和 test 基于 build 实现**

之前是基于中间件实现的，和 build 的流方式是两套。所以，调整方案之后：

- 稳定性更好：不会存在调试通过后，构建出来的代码有问题的情况
- 维护成本更低：仅需维护一套方案
- 文档静态化：doc 生成的文档终于静态化了，可部署到任意地方

**还有一些其他的变更点：**

- 内置 server ：不再需要额外安装命令就可进行项目调试了
- [spm-sea](https://github.com/spmjs/spm-sea)：spm 只内置 standalone 方式的打包，cmd 方式抽取成 spm-sea，不再内置
- css 包规则变更：`@import '~foo'` 表示 foo 模块，`@import 'foo'` 表示 foo 文件，[讨论](https://github.com/spmjs/spm-sea/issues/2)

**文档教程：**
- [升级到 3.6](https://github.com/spmjs/docs/blob/master/misc/upgrade-to-3.6.md)
- [例子](https://github.com/spmjs/examples/tree/spm-webpack#examples)
- [项目入门](https://github.com/spmjs/docs/blob/master/project/get-started.md)
- [组件入门](https://github.com/spmjs/docs/blob/master/package/get-started.md)

**感谢：**
- 在项目中应用并帮忙采坑的同学们 (已有 6 个内部项目实践过此方案)
- webpack

--

云谦
2015.4.16

**Comment by afc163** [comment]
前排就坐，文档静态化非常赞。

**Comment by popomore** [comment]
快快用起来
偏右 <notifications@github.com>于2015年4月16日 周四下午1:12写道：

**Comment by iyutao** [comment]
前排～

**Comment by SMbey0nd** [comment]
webpack太赞了，解决了之前好多头痛的问题，尤其是server与build阶段解析引擎不一致的问题。
项目密切深度使用中。

**Comment by afc163** [comment]
文档现在分布的有点散，后续可以整理一下。

**Comment by xudafeng** [comment]
越来越强大

**Comment by jsw0528** [comment]
火钳留名

**Comment by superRaytin** [comment]
赞！

**Comment by alvin2ye** [comment]
#1252 出错 你们都没遇到吗?

**Comment by alvin2ye** [comment]
@sorrycc 原来是CMD的, 不想马上改回来, 改动太大. 

package.json 要怎么配置, 我有看到说用 spm-sea 但用法不知道

**Comment by sorrycc** [comment]
CMD 的可以用 spm-sea (构建，3.4 的配置方法) + spm-server (调试) 。

**Comment by alvin2ye** [comment]
过了这个SP 我再升级到 3.6 现在赶交期.

**Comment by liangwind** [comment]
按docs/zh-cn/package/get-started.md 进行，到 spm doc 出现如下错误：求教
E:\git\lc>spm doc

         target: http://spmjs.io
        install: expect.js@0.3.1
          found: expect.js@0.3.1

          build: compile
          error: Module not found: Error: a dependency to an entry point is not
allowed
      generated: index.js 104.75kB
      generated: ./bundle.js 1.68kB
      generated: index.js.map 119.30kB
      generated: ./bundle.js.map 1.61kB
          build: done

          build: compile
          build: invalid
          build: compile
          error: Module not found: Error: a dependency to an entry point is not
allowed
      generated: index.js 104.75kB
      generated: ./bundle.js 1.68kB
      generated: index.js.map 119.30kB
      generated: ./bundle.js.map 1.61kB
          build: done
          error: Module not found: module webpack amd options not found
      generated: test.js 985.19kB
      generated: test.js.map 1336.11kB
          build: done

           nico: 0.5.3
           load: C:/Users/tsjy/AppData/Roaming/npm/node_modules/spm/lib/theme/ni
co.js
           load: PageWriter
           load: StaticWriter
           load: FileWriter
           load: MochaWriter
            run: PageWriter
          write: 3 pages
            run: StaticWriter
           copy: C:/Users/tsjy/AppData/Roaming/npm/node_modules/spm/lib/theme/st
atic -> _site/static
            run: FileWriter
            run: MochaWriter
           time: 3.27s
           load: C:/Users/tsjy/AppData/Roaming/npm/node_modules/spm/lib/theme/ni
co.js
           warn: npm install socket.io to enable livereload
          watch: E:\git\lc
          watch: C:\Users\tsjy\AppData\Roaming\npm\node_modules\spm\lib\theme
         server: http://127.0.0.1:8000

**Comment by lichunqiang** [comment]
执行 `spm doc` 之后 `_site` 目录没有生成 `static` 文件夹
