### ISSUE TITLE
build 参数中设置 handlebars 为 global，无效

### ISSUE THREAD

**Issue by crossjs** [spmjs/spm#1259]
rt，仅 jquery 替换成功
```
"buildArgs": "--sea all --global jquery:util.$,handlebars:util.template,handlebars-runtime:util.template --skip source-map --idleading /{{name}}"
```
何解？

**Comment by sorrycc** [comment]
util 是全家变量?

**Comment by crossjs** [comment]
是的。

引起的原因应该是 spm-build 对 handlebars 是特殊处理的？
目前的排查结果，应该可在 `gulp-spm/lib/plugin/js.js` 里解决问题。

**Comment by sorrycc** [comment]
考虑下 standalone 的方案吧 (3.6)，坑比较少。

**Comment by lynzz** [comment]
我用 3.6 的方案，设置handlebars 为全局时，require('./xxx.handlebars') 里的 handlebars 引用的不是全局的 handlebars

**Comment by sorrycc** [comment]
require xxx.handlebars 会触发预编译机制，这种情况下不要 global handlebars 。

**Comment by sorrycc** [comment]
在直接 require('handlebars') 来解析模板的时候可以配 global
