### ISSUE TITLE
在哪里可以查询官网线上模块的部署情况？

### ISSUE THREAD

**Issue by stoneChen** [spmjs/spm#1264]
RT
比如支付宝页面上的https://a.alipayobjects.com/??seajs/seajs/2.2.3/sea.js,seajs/seajs-combo/1.0.0/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.0/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js,alipay-request/3.0.3/index.js

其他公司可以无偿使用吗？

**Comment by afc163** [comment]
不拒绝不主动不负责。
