### ISSUE TITLE
spm doc 的时候，一旦出错，watch任务就crash了

### ISSUE THREAD

**Issue by stoneChen** [spmjs/spm#1265]
比如require一个不存在的模块，直接就crash掉了，需要重新执行spm doc，有点不方便，希望改进一下。可以参考下这个，希望有帮助 http://stackoverflow.com/questions/5999373/how-do-i-prevent-node-js-from-crashing-try-catch-doesnt-work

**Comment by sorrycc** [comment]
现在 require 不存在的模块不会直接 crash 了。
