### ISSUE TITLE
改进出错提示，更友好，便于排查问题

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1266]
先列下已经遇到的：

- [x] 基本信息不对，比如 output 属性不是数组时
- [x] package.json 解析错误时
- [x] 端口被占用的错误信息可以更语义化
- [ ] css 书写有问题时，报错不明显。比如 .a { background:url(); }
- [x] less 编译出错时，报 `error: Module build failed: Error: Didn't get a result from child compiler`

**Comment by ziluo** [comment]
增加一条：
+ 端口被占用的错误信息可以更语义化，而且这个错误经常遇到，如果可以的话，最好能做到自动切换到别的端口

**Comment by sorrycc** [comment]
- CSS 书写有问题时，报错不明显。比如 `.a { background:url(); }`

**Comment by sorrycc** [comment]
先 close 了，css 书写问题那条通过换 css 压缩器解决。
