### ISSUE TITLE
Allocation failed - process out of memory 

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1267]
```bash
➜  static git:(dev) ✗ spm server --livereload
      webserver: listened on 8000
    css deleted: filter: progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0); in $CWD/spm_modules/recordselect/0.1.7/css/recordselect.css
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
➜  static git:(dev) ✗ spm --version
3.6.0
```

----

 3.4 是好的.

**Comment by sorrycc** [comment]
重启下电脑试试，没遇到过内存溢出的情况。

**Comment by afc163** [comment]
看上去和处理 css 的 filter 有关系。可以把项目搞出来看看。

**Comment by alvin2ye** [comment]
@afc163 我把项目中的CSS 删掉, 一样还是溢出.

```
spm build --verbose
```
停在这里

![image](https://cloud.githubusercontent.com/assets/5401/7224102/4852dafc-e760-11e4-8aeb-20520580351a.png)

**Comment by alvin2ye** [comment]
8G 内存

➜  static git:(dev) ✗ spm --version
3.6.0
➜  static git:(dev) ✗ node --version
v0.12.0


![image](https://cloud.githubusercontent.com/assets/5401/7224122/891a3044-e760-11e4-8931-a0595dc9c46c.png)

**Comment by sorrycc** [comment]
配置下不处理 buffer 试试：

```
"spm": {
  "build": {
    "node": {"buffer":false}
  }
}
```

https://github.com/spmjs/docs/blob/master/project/configuration.md#node

**Comment by alvin2ye** [comment]
一个个排查后发现了 tpl 问题
![image](https://cloud.githubusercontent.com/assets/5401/7224314/1b6260aa-e763-11e4-889f-b990cd2c0680.png)


原来的tpl 不支持了?


![image](https://cloud.githubusercontent.com/assets/5401/7224320/35baca0a-e763-11e4-80cd-742ad795c2ce.png)

是 xs.art-template

**Comment by sorrycc** [comment]
- `.tpl` 是支持的，会做去换行之类的简单转换
- xs.art-template ? 之前也没有用这个来转 tpl 啊

**Comment by alvin2ye** [comment]
3.4.3 全正常

**Comment by sorrycc** [comment]
已修复，和 #1288 是同一个问题。
