### ISSUE TITLE
aliceui 主站无法用 spm@3.6 进行 build

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#1270]
https://github.com/aliceui/aliceui.org/

**Comment by sorrycc** [comment]
尝试了下，不好改啊，因为需要让 html, iframe 等 tag 里的 scripts 都支持 commonjs。下周我再看下。

**Comment by sorrycc** [comment]
https://github.com/aliceui/aliceui.org/pull/68/files
已升级到 3.6
