### ISSUE TITLE
关于 registry 

### ISSUE THREAD

**Issue by nimojs** [spmjs/spm#1273]
问题来源
https://github.com/seajs/seajs/issues/1488#issuecomment-95124932

<blockquote>
我对 spm3 的理解对吗？

那我在实际写业务模块的时候 不是很麻烦么。并且我上传的业务模块不是大家能用的。

我也并不希望敏感的 业务模块上传到spmjs.io上。

这时候 我怎么使用spm3呢？
</blockquote>
@honger05 遇到的问题是不想发布到 spmjs.io

----

我遇到的问题是有时 spmjs.io 上主流的模块已被占坑，而我想使用最新版。而我没有权限publish。

这时我希望我能够直接在本地 spm_modules 目录下存放spmjs.io没有的的模块

当我在 spm_modules 存放一个 local 模块，并 `spm server`
会出现如下错误提示

```
           exit: Not found. ~ http://spmjs.io/repository/local/0.0.1/
```

查阅文档后发现可以在 `package.json` 指定 `registry` 目标，但我只想使用本地的 spm_modules 。

可否提供 `local` 参数：

------

```
"local_modules":  {
   "some": "0.0.1"
}```

使用 `spm server` `spm build` 等功能都会直接使用 local_modules 里面的内容。

**Comment by sorrycc** [comment]
#821

**Comment by sorrycc** [comment]
- 试了下，本地 spm_modules 下有相应版本的文件时，不会发起远程请求的
- 可以通过 spm link 快速软链另一个包到当前的 spm_modules 文件夹下
- local 依赖的功能我在下个版本 (3.7) 里加下，#821

**Comment by nimojs** [comment]
1. 我本地又试了一下可以的，上午测试不行可能是我漏掉 package.json 之类的原因
2. `spm link` 功能是什么，没有找到相关的文档

我准备将 spm_modules 目录下存放本地包并使用的教程增加至 [spmjs/docs](https://github.com/spmjs/docs),你看合适吗？ 还是等 3.7 的 local 功能出现后直接更新 local 的示例？

**Comment by sorrycc** [comment]
spm_modules 本地存放包并不是推荐的方式啊，因为通常会在 `.gitignore` 里忽略他的。推荐的方式是 spm link 和 3.7 的 local 。

spm link 类似 npm link，用于把另一个包软链到当前项目中。
