### ISSUE TITLE
spm server 支持 hash:true 的场景

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1274]
- server 时手动删 hash 配置, [code](https://github.com/spmjs/spm-webpack-server/blob/master/cli.js#L41)
- 中间件里遇到带 hash 后缀，要删除, [code](https://github.com/spmjs/spm-webpack-server/blob/master/middleware.js)

**Comment by pigcan** [comment]
实际feature新增的时候发现

在webpack-server cli中通过调用spm-webpack的getWebpackOpts方法调用过一次package.json的内容，

而在getWebpackOpts方法体内又调用一次package.json的内容，导致两次读取。

现统一只读取一遍package.json的内容，然后在server的情况下，把配置项中的hash人为置为false. 那全局生效。 所以 中间件就不用修改任何代码了。

**Comment by sorrycc** [comment]
Fixed via spm-webpack-server@0.3.2
