### ISSUE TITLE
3.6版本 doc时报错  Arguments to path.join must be strings

### ISSUE THREAD

**Issue by chouxiaozi** [spmjs/spm#1275]
node版本0.12.2  npm 版本2.7.4 spm版本3.6.0 
在[组件入门](https://github.com/spmjs/docs/blob/master/package/get-started.md)的时候执行到spm doc出现错误，请问应该怎么解决。

**Comment by sorrycc** [comment]
windows ?

**Comment by chouxiaozi** [comment]
windows 64

**Comment by sorrycc** [comment]
重复了，这个先关了。

**Comment by chouxiaozi** [comment]
那我回退一个版本？到版本几？

**Comment by chouxiaozi** [comment]
那我回退一个版本？到版本几？
