### ISSUE TITLE
主流模块定期更新计划

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#1276]
现在 spmjs.io 上的一些著名模块的版本更新不力，需要安排专员列出来进行更新。

**Comment by hotoo** [comment]
开发 4.0, 直接使用 npm 源 XD

**Comment by sorrycc** [comment]
著名模块感觉好多啊

**Comment by nimojs** [comment]
> 著名模块感觉好多啊 
:+1:  太多了

即使有专员更新也解决不了问题

能否当 spm install handlebars@3.0.0 时找不到 spmjs.io 上的模块就直接down npm上的

**Comment by nimojs** [comment]
请问这个计划现在进度如何了，最近使用 spm 经常遇到线上没有某些模块的最新版。导致只能用老版的。

**Comment by sorrycc** [comment]
@nimojs 这个需求比较强烈，已提高这件事的优先级，预计 5 月底提供 spm-sync 的辅助工具，用于同步 npm 上的包到 spmjs.io 。#1202

**Comment by sorrycc** [comment]
#1309
