### ISSUE TITLE
对于spm不得不说的几个问题

### ISSUE THREAD

**Issue by justnode** [spmjs/spm#1279]
## 你们强烈推荐使用standalone的构建方式是什么
我按照arale官网上[地址](http://aralejs.org/docs/develop-components.html)的文档一步步操作，spm build --standalone 后，我在dist目录中看到了构建后的文件，define包裹的代码，依赖也提取出来了，但是这个文件怎么引用？官网上说：

`
    <script src="build.js"></script>
`

敢问这里的build.js到底是那个文件？如果是指构建好的文件，被define包裹的代码如何在浏览器端运行？ 这是什么新技术？ 

我试着用seajs加载构建后的文件，ok，代码正常运行了。这里的standalone莫非是把依赖的文件都打包到构建后的文件？ 只是个人猜测，官网上的文档找不到任何根据，连官网的实例文档都写的云里雾里，文档真的是写给新手看的吗？

## 构建后的模块名以/开头，这是几个意思？

`
    define("/index",["arale-popup/1.2.0/popup","jquery/1.7.2/jquery"
`

去掉index前的斜杠后，用seajs加载才能正常，总不能每次构建后都人肉修改吧。。。。。。

## 如果我希望构建后的文件不被压缩，uglify的参数要如何配置

七找八找的，还是没找到每个配置参数的说明，额，已经无力吐槽 

###  最后不得不提一句：用纯前端的思维解决模块化问题注定是一条死胡同，前端模块化无非就是模块的拆分和合并，但是如果模块的合并放在前端来做的话，模块的后期维护和升级将会是恶梦。

**Comment by nimojs** [comment]
> 由相关页面没有指向最新的文档页面来背黑锅吧

请看最新文档 https://github.com/spmjs/docs

请讲 standalone 理解为直接在页面中用 script 载入就可以运行的一个js文件

如果你用 seajs 作为模块加载器，可以看下这个项目 [seajs-cmd](https://github.com/nimojs/seajs-cmd)(使用nginx-http-concat 配合 seajs-combo 在线打包)

-----

spm3 已经不是 seajs 的打包工具了，而是使用完全本地打包的方式进行模块化开发。生态环境是 http://spmjs.io/


-----

seajs 打包可以用 https://github.com/spmjs/spm-sea

**Comment by justnode** [comment]
很感谢你的回答，不过那个最新文档中没有我想要的答案，standlone的概念还是云里雾里，我用spm3.4 standlone构建出来的文件是define包裹的，不是一个可以运行的js文件，莫非需要用3.6才行？

### 呼吁一句：文档写的详细点吧 ...

**Comment by nimojs** [comment]
是的，请使用3.6
build 后就是能直接执行的js文件,不需要任何模块加载器加载调用

**Comment by afc163** [comment]
standalone

不是 

standlone

我估计打错了。

**Comment by justnode** [comment]
ok  用了3.6 解决问题 多谢楼上两位的耐心解答  ^_^
