### ISSUE TITLE
Arale-dialog组件通过spm3编译后出现如下错误

### ISSUE THREAD

**Issue by blowxian** [spmjs/spm#1283]
Arale-dialog组件通过spm3编译后出现如下错误：
![image](https://cloud.githubusercontent.com/assets/1855830/7415724/5e3ddc24-ef8d-11e4-8f48-eca464ff03c9.png)
貌似是Overlay组件内的代码被编译错了。

**Comment by sorrycc** [comment]
这个看起来是对的啊，执行的时候报错?

**Comment by blowxian** [comment]
编译后，入参不包含module，函数体内仍然使用了module @sorrycc

**Comment by sorrycc** [comment]
试试升级 spm 到 3.6 ?

**Comment by blowxian** [comment]
![image](https://cloud.githubusercontent.com/assets/1855830/7666895/db262870-fc28-11e4-86a7-de0a429aa677.png)
升级到spm@3.6后问题仍然存在！
