### ISSUE TITLE
关于 spmjs.io/doc 不区分路径大小写

### ISSUE THREAD

**Issue by nimojs** [spmjs/spm#1284]
我的包是 http://spmjs.io/package/paging 

在 http://spmjs.io/docs/paging/latest/examples/index.html 页面点击左侧的 [控制前后几页显示数量](http://spmjs.io/docs/paging/latest/examples/beforePageCount.html)
http://spmjs.io/docs/paging/latest/examples/beforePageCount.html 不可访问
http://spmjs.io/docs/paging/latest/examples/beforepagecount.html 可访问

**Comment by sorrycc** [comment]
用中划线或下划线进行连接吧，服务器的环境问题，上次搞好久没搞定。
