### ISSUE TITLE
关于跨js组件调用问题

### ISSUE THREAD

**Issue by eternalsky** [spmjs/spm#1285]
抱歉，问题的名字不知道怎么起好，我描述下具体的使用场景。
spm3.6之后使用webpack的打包方式，将所有代码和依赖打成一个js文件，本身是一个IIFE的闭包。那么比如我在这个js中require了一个组件，如何在另一个js中使用他。(业务的需要，另一个js的代码不能和第一个js打在一起，也可能甚至不用spm-webpack打包)。是挂在window变量下吗，官方有没有推荐的实践方式？

**Comment by sorrycc** [comment]
https://github.com/spmjs/docs/blob/master/project/configuration.md#global
看下 `global` 参数能否满足需求?
