### ISSUE TITLE
spm build -s 之后生成的js含有define

### ISSUE THREAD

**Issue by fly3q** [spmjs/spm#1290]
你好，请问编译生成的js代码中，是以define开头的，引用到html中就不能执行了。而且生成的文件中并没有xxx-debug.js文件，spm版本为3.4.2。 
编译命令为: spm build -s --skip crypto
![image](https://cloud.githubusercontent.com/assets/194304/7508097/a7f19062-f4ac-11e4-94b0-52164738bb4b.png)
之前编译生成的都是以!function 开头，请问是什么原因？
![Uploading image.png…]()

**Comment by sorrycc** [comment]
执行 `spm build` 时的输出贴上来看下?

**Comment by fly3q** [comment]
[user_00@h0000 src-js]$ spm build -s -f --verbose --skip crypto

          start: build ttyd@0.0.1
      arguments: cwd = $CWD
      arguments: dest = $CWD/dist
      arguments: zip = false
      arguments: force = true
      arguments: withDeps = false
      arguments: install = true
      arguments: ignore = []
      arguments: skip = ["crypto"]
      arguments: idleading = {{name}}/{{version}}
      arguments: global = {}
      arguments: uglify = {"output":{"ascii_only":true}}
      arguments: cssmin = {}
      arguments: entry = []
      arguments: registry = http://spmjs.io
      arguments: main = ttyd.js
      arguments: dependencies = {"jquery":"2.1.3","jquery-cookie":"1.4.1","md5":"2.0.0"}
      arguments: devDependencies = {"expect.js":"0.3.1"}
      arguments: output = ["report.js","ttid.js","exposure.click.js"]
      arguments: standalone = true
      arguments: originPkg = {"name":"ttyd","version":"0.0.1","description":"ttyd js sdk","keywords":[],"homepage":"","author":"wuzejun <zejun.wu@ttyoudao.com>","repository":{"type":"git","url":""},"bugs":{"url":""},"licenses":"MIT","spm":{"main":"ttyd.js","dependencies":{"jquery":"2.1.3","jquery-cookie":"1.4.1","md5":"2.0.0"},"devDependencies":{"expect.js":"0.3.1"},"output":["report.js","ttid.js","exposure.click.js"]},"devDependencies":{"spm":"3"},"scripts":{"test":"spm test","build":"spm build"}}
      arguments: include = standalone
        install: expect.js@0.3.1
          found: expect.js@0.3.1
        install: jquery@2.1.3
          found: jquery@2.1.3
        install: jquery-cookie@1.4.1
          found: jquery-cookie@1.4.1
        install: md5@2.0.0
          found: md5@2.0.0
        package: analyse infomation
        package: dependencies: jquery,jquery-cookie,md5
        package: files: ttyd.js,report.js,util.js,ttid.js,json.js,exposure.click.js
         output: files: exposure.click.js,report.js,ttid.js,ttyd.js
     extra deps: no
          clean: $CWD/dist
           size: ttyd/0.0.1/exposure.click.js 5.40kB (gzipped)
           size: ttyd/0.0.1/report.js 5.97kB (gzipped)
           size: ttyd/0.0.1/ttid.js 4.91kB (gzipped)
  generate file: dist/ttyd/0.0.1/exposure.click.js
           size: ttyd/0.0.1/ttyd.js 5.99kB (gzipped)
           size: total 22.27kB (gzipped)
  generate file: dist/ttyd/0.0.1/exposure.click.js
  generate file: dist/ttyd/0.0.1/report.js
  generate file: dist/ttyd/0.0.1/report.js
  generate file: dist/ttyd/0.0.1/ttid.js
  generate file: dist/ttyd/0.0.1/ttid.js
  generate file: dist/ttyd/0.0.1/ttyd.js
  generate file: dist/ttyd/0.0.1/ttyd.js
         finish: build ttyd@0.0.1 (1954ms)

这边的输出应该xxx-debug.js 文件的

**Comment by fly3q** [comment]
配置文件是这样的，我在另外一个机器上编译到时好的，两台机器的版本都是v3.4.2。奇怪的很
{
  "name": "ttyd",
  "version": "0.0.1",
  "description": "ttyd js sdk",
  "keywords": [],
  "homepage": "",
  "author": "",
  "repository": {
    "type": "git",
    "url": ""
  },
  "bugs": {
    "url": ""
  },
  "licenses": "MIT",
  "spm": {
    "main": "ttyd.js",
    "dependencies": {
      "jquery": "2.1.3",
      "jquery-cookie": "1.4.1",
      "md5": "2.0.0"
    },
    "devDependencies": {
      "expect.js": "0.3.1"
    },

    "output": [
      "report.js",
      "ttid.js",
      "exposure.click.js"
    ]
  },
  "devDependencies": {
    "spm": "3"
  },
  "scripts": {
    "test": "spm test",
    "build": "spm build"
  }
}

**Comment by sorrycc** [comment]
诡异了。。看输出没错，有 `arguments: include = standalone`，理论上不会输出 `define` 这种格式的。

**Comment by fly3q** [comment]
神奇的很，
npm uninstall spm，
重装之后也不行。

**Comment by fly3q** [comment]
另外一台机子编译的是这样的。
 start: build ttyd@0.0.1
     Deprecated: buildArgs.include is deprecated, using sea, standalone and umd instead.
      arguments: cwd = $CWD
      arguments: dest = $CWD/dist
      arguments: zip = false
      arguments: force = false
      arguments: withDeps = false
      arguments: install = true
      arguments: ignore = []
      arguments: skip = []
      arguments: idleading = {{name}}/{{version}}
      arguments: global = {}
      arguments: uglify = {"output":{"ascii_only":true}}
      arguments: cssmin = {}
      arguments: entry = []
      arguments: registry = http://spmjs.io
      arguments: main = ttyd.js
      arguments: dependencies = {"jquery":"2.1.3","jquery-cookie":"1.4.1","md5":"2.0.0"}
      arguments: devDependencies = {"expect.js":"0.3.1"}
      arguments: include = standalone
      arguments: output = ["report.js","ttid.js","exposure.click.js"]
      arguments: originPkg = {"name":"ttyd","version":"0.0.1","description":"ttyd js sdk","keywords":[],"homepage":"","author":"wuzejun <zejun.wu@ttyoudao.com>","repository":{"type":"git","url":""},"bugs":{"url":""},"licenses":"MIT","spm":{"main":"ttyd.js","dependencies":{"jquery":"2.1.3","jquery-cookie":"1.4.1","md5":"2.0.0"},"devDependencies":{"expect.js":"0.3.1"},"include":"all","output":["report.js","ttid.js","exposure.click.js"]},"devDependencies":{"spm":"3"},"scripts":{"test":"spm test","build":"spm build"}}
        install: expect.js@0.3.1
          found: expect.js@0.3.1
        install: jquery@2.1.3
          found: jquery@2.1.3
        install: jquery-cookie@1.4.1
          found: jquery-cookie@1.4.1
        install: md5@2.0.0
          found: md5@2.0.0
        package: analyse infomation
        package: dependencies: jquery,jquery-cookie,md5
        package: files: ttyd.js,report.js,util.js,ttid.js,json.js,exposure.click.js
         output: files: exposure.click.js,report.js,ttid.js,ttyd.js
     extra deps: no
           size: ttyd/0.0.1/exposure.click.js 34.01kB (gzipped)
           size: ttyd/0.0.1/report.js 5.92kB (gzipped)
  generate file: dist/ttyd/0.0.1/exposure.click-debug.js
           size: ttyd/0.0.1/ttid.js 4.89kB (gzipped)
           size: ttyd/0.0.1/ttyd.js 5.94kB (gzipped)
           size: total 50.75kB (gzipped)
  generate file: dist/ttyd/0.0.1/report-debug.js
  generate file: dist/ttyd/0.0.1/exposure.click.js
  generate file: dist/ttyd/0.0.1/report.js
  generate file: dist/ttyd/0.0.1/ttid-debug.js
  generate file: dist/ttyd/0.0.1/ttid.js
  generate file: dist/ttyd/0.0.1/ttyd-debug.js
  generate file: dist/ttyd/0.0.1/ttyd.js
         finish: build ttyd@0.0.1 (8743ms)

多一个xxx-debug.js 这样的文件。

**Comment by fly3q** [comment]
请问有什么解决方法吗？谢了

**Comment by afc163** [comment]
dist 目录先删掉再试试？

**Comment by fly3q** [comment]
删了卸载重装都不行，诡异的很

**Comment by sorrycc** [comment]
已修复，重装 SPM 即可。同 #1299
