### ISSUE TITLE
spm3.6.0 build 命令不支持 --sea 么

### ISSUE THREAD

**Issue by OoOChrisChan** [spmjs/spm#1291]
![sea](https://cloud.githubusercontent.com/assets/983502/7512535/40a8f90c-f4e0-11e4-8b16-424ff66b5e04.png)

![spmdoc](https://cloud.githubusercontent.com/assets/983502/7512552/5fd1307e-f4e0-11e4-8dab-2180ba474232.png)

**Comment by sorrycc** [comment]
3.6 不内置 cmd 方式的构建，请使用 https://github.com/spmjs/spm-sea

**Comment by OoOChrisChan** [comment]
哪里可以看spm的更新日志呀
