### ISSUE TITLE
spm publish 在 node 0.12 下生成的 tar 包内容路径不对

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1292]
见下图，在包里面多生成了一个 `chat` 文件夹，包含所有源码的文件夹。

![image](https://cloud.githubusercontent.com/assets/35128/7530080/fd19e828-f574-11e4-9505-6912a2e5d606.png)

node 0.12 下的问题，node 0.11 正常。

**Comment by afc163** [comment]
应该是依赖包升级的问题，实测 0.11 也有问题。

**Comment by sorrycc** [comment]
早上排查的时候发现又好了。。估计某个依赖包升级后出错，然后今天又升级了下修复了。
