### ISSUE TITLE
spm doc require的转换不彻底，导致 Demo 无法跑起来

### ISSUE THREAD

**Issue by yize** [spmjs/spm#1295]
See demo：[http://spmjs.io/docs/arale-dialog/examples/confirmbox.html]( http://spmjs.io/docs/arale-dialog/examples/confirmbox.html)

Error: 
```
iframe-confirmbox-1.html:33 Uncaught ReferenceError: require is not defined
```

HTML:
![image](https://cloud.githubusercontent.com/assets/1578814/7557418/c7491e3e-f7c3-11e4-9c7a-eccba26fa9c3.png)

Reason:
`require('arale-dialog')` 并没有转换成 `window['arale-dialog']`

**Comment by sorrycc** [comment]
html 的转化还没支持，只支持了 javascript 的转换。

**Comment by yize** [comment]
@sorrycc 嗯，有排在计划中吗？

**Comment by sorrycc** [comment]
同 #1270，改起来有点麻烦。先用四个 ` 的 javascript 把 js 从 html 中分离出来单独写吧。

**Comment by sorrycc** [comment]
这个先关了，关注 #1270 。

**Comment by kangning1206** [comment]
凡是 examples 中使用 iframe ，只能取消 iframe，spm2 转化 spm3 demo 成本太大。
````iframe:200
<script>
// 此处不知不好
</srctipt>
````

**Comment by sorrycc** [comment]
@kangning1206 iframe 中用可以直接写全局变量。
