### ISSUE TITLE
spm build的css没有压缩

### ISSUE THREAD

**Issue by zinkey** [spmjs/spm#1298]
package中："extractCSS": true
spm build后，由less文件生成的css文件，没有被压缩

**Comment by sorrycc** [comment]
是经过压缩的，可以直接上线。webpack 在压缩后，如果发现有 background 声明，就会又把 css 格式化掉，估计是为了取 url 资源做某些处理吧。

不过这个问题被不少人提到了，可以作为一个优化点，但优先级低。
