### ISSUE TITLE
spm build --with-deps执行失败

### ISSUE THREAD

**Issue by wnow20** [spmjs/spm#1302]
发现：spm build --with-deps 并不能执行
提示：error: unknown option `--with-deps'

但是可以执行，spm-build --with-deps，成功，这算是bug么？

系统环境：window 8.1 pro x64
Node version: v0.12.2
Spm version: 3.6.0

**Comment by sorrycc** [comment]
spm 3.6 之后，cmd 相关的构建没有内置在 spm 中，已抽离到 [spm-sea](https://github.com/spmjs/spm-sea) 中。

你可以试试：

```bash
$ npm i spm-sea -g
$ spm-sea --with-deps
```
