### ISSUE TITLE
spm 3.6 build 卡死, 请问怎么排查

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1303]
![image](https://cloud.githubusercontent.com/assets/5401/7671279/e214f670-fcfa-11e4-81cc-5b96d81d7b4a.png)

日志中spm_modules/events/1.0.1/events.js 我已经重新下载过, 并进入 events 目录编译过, 没有问题.

**Comment by sorrycc** [comment]
package.json 中的 spm -> build 下禁用 node 的 process 模块解析试试：

```
"node": {
  "process": false
}
```

https://github.com/spmjs/docs/blob/master/project/configuration.md#node

**Comment by alvin2ye** [comment]
可以了
