### ISSUE TITLE
spm 3.6 但还是想打包成 seajs 要怎么配置?

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1304]
文档中有提到用 spm-sea, 但不知道怎么用

**Comment by sorrycc** [comment]
和之前一样用啊，可以 `spm-sea -h` 看下配置项。

https://github.com/spmjs/spm-sea

**Comment by alvin2ye** [comment]
spm-sea 只是过渡下, 以后会不会维护的.

**Comment by sorrycc** [comment]
一年内肯定还是维护的，我们基于 seajs 的组件发布是基于这部分的。

**Comment by alvin2ye** [comment]
好的, 谢谢
