### ISSUE TITLE
3.6 版本没有standalone 这个build 选项？

### ISSUE THREAD

**Issue by zzhdi** [spmjs/spm#1308]
在文档中有下面一段
>And We strongly recommend building a standalone package by adding an argument.
>$ spm build --include standalone

我安装了最新的Spm，提示没有standalone 这个选项，是我环境配置不正确吗？
![image](https://cloud.githubusercontent.com/assets/4590934/7716971/14ea6058-fecc-11e4-9a3a-ffaa124f8b63.png)

**Comment by sorrycc** [comment]
文档过时了，还没更新。先看这里的：https://github.com/spmjs/docs

spm 3.6 默认就是 standalone 模式的，所以不需要再加这个参数。

**Comment by zzhdi** [comment]
![image](https://cloud.githubusercontent.com/assets/4590934/7717581/7c1e101c-fed6-11e4-900f-b931031abedd.png)
这里面提到了3个组件，他们使用的场景是什么？

**Comment by zzhdi** [comment]
@sorrycc 如何配置打包策略？
