### ISSUE TITLE
讨论：npm 源的手动同步方案

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1309]
一开始是想放在命令行里做的，后来想想感觉放在源服务器上做更合适。虽然会给服务器造成一些压力，但是由于可以通过本地读文件访问已有的包信息，所以会更快一些，另外也可以通过 web 界面进行操作。

**API：**

- `/repository/sync/package` - 同步包的所有版本
- `/repository/sync/package/version` - 同步包指定版本

**spmjs.io 上接受到请求之后的逻辑：**

1. 认证用户是否登录 (否 -> 退出)
1. 开子进程
1. 请求包数据 (请求失败或 404 -> 退出)
1. 尝试同步包的指定版本
1. 检查当前包是否可以被同步 (否 -> 退出)
1. 获取依赖树，拍平
1. 检查依赖树中是否有不可以被同步的包 (有 -> 退出)
1. 循环处理 -> 同步包的指定版本
1. 从 npm 源上下载 tar 包 (下载失败 -> 退出)
1. 解压、验证 md5 (失败 -> 退出)
1. 修改 package.json
  - 处理 spm, main, dependencies
  - 不处理 devDependencies
  - 验证 name/version 是否符合 spm 的规则
  - 检查 main 文件是否存在
  - ...
1. 以用户的认证信息 publish 到当前服务器
1. 标记为可 sync 的包

**Comment by sorrycc** [comment]
已完成。

**Comment by nimojs** [comment]
请问这个功能普通用户如何使用？

**Comment by afc163** [comment]
README 信息也同步一下吧。
