### ISSUE TITLE
doc 的问题和需求梳理

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1310]
@afc163 

1. 处理 examples 下的 html，`<script>` 支持相对文件的引用
1. markdown 中的 require 支持相对文件的引用
1. 过滤掉 _site 目录中的冗余的 commonjs 文件

@dxq613

1. fix: tests/runner.html 默认不生成覆盖率，传入 `?cov` 参数后生成

其他：

1. markdown 中的 require 转换支持 iframe 和普通的 `<script>` 标签

**Comment by afc163** [comment]
保持演示中使用方式和真实场景的使用方式的一致：

1. 真实场景中在 JS 中调用用 `require`。
    演示中 JS 里也使用 `require` 来调用。

2. 真实场景中在 HTML 中调用用 `<script>`。
    演示中 HTML 里也使用 `<script>` 来调用。

都支持相对路径（展示时显示包名？）。
