### ISSUE TITLE
spmjs.io上的jquery和官网差一个版本，麻烦升级到最新（1.11.3，2.1.4）

### ISSUE THREAD

**Issue by h1bomb** [spmjs/spm#1317]
麻烦@afc163 @popomore  @sorrycc 诸位维护者升级下，谢谢
地址：http://spmjs.io/package/jquery

**Comment by jsw0528** [comment]
为啥不自己 publish？

**Comment by afc163** [comment]
2.1.4 published

**Comment by sorrycc** [comment]
1.11.3 published
