### ISSUE TITLE
spm3.6如何启用sourceMap?

### ISSUE THREAD

**Issue by MaxLee1994** [spmjs/spm#1318]
系统环境：OS X 10.10.3
                  spm 3.6

package.json配置如下：
![2015-06-01 11 43 17](https://cloud.githubusercontent.com/assets/5857749/7905923/a1f65214-0853-11e5-8eb2-f783d7eb0e04.png)

然而`spm build`后并没有生成sourceMap啊？

**Comment by afc163** [comment]
https://github.com/spmjs/docs/blob/master/zh-cn/project/configuration.md#devtool

http://webpack.github.io/docs/configuration.html#devtool
