### ISSUE TITLE
examples markdown 中 ````js 无法获得依赖

### ISSUE THREAD

**Issue by hotoo** [spmjs/spm#1325]
1. 需要重启 `spm doc watch` 才可以获得更新的 require.
2. 需要使用 `~~~~javascript`，不支持 `~~~~js`，以前是支持的。（~替换成`）

**Comment by afc163** [comment]
1. 要保存第二次才能获得前一次的更新。。。

**Comment by sorrycc** [comment]
1. doc build 有问题，没有执行 spm-webpack 的构建操作

**Comment by sorrycc** [comment]
都搞定了。
