### ISSUE TITLE
添加了 name, version 之后无法调试 v3.6.2

### ISSUE THREAD

**Issue by matin0728** [spmjs/spm#1331]
就是那个 countdown 的例子，将 package.json 改为:
   {
	"name": "test1",
        "version": "0.0.1",
        "spm": {
            "dependencies": {
               "util": "~0.10.3",
               "moment": "~2.10.3",
               "arale-popup": "~1.2.0"
           }
        }
   }

之后，在本地调试的时候引用的 js 都没有 require 的头了，提示 require 未定义.

**Comment by sorrycc** [comment]
请求的 url 是啥? 给个可重现的代码看看。

**Comment by pigcan** [comment]
@sorrycc  应该就是前几天 `spm-webpack-server@0.4.2` 解决的问题 

更新下`spm`应该就好了
