### ISSUE TITLE
图片url 带版本号参数会导致打包出错

### ISSUE THREAD

**Issue by wuguanghai45** [spmjs/spm#1332]
http://spmjs.io/package/font-awesome
引用font-awesome的时候抛错
error: Module build failed: Error: Cannot find module "../fonts/fontawesome-webfont.eot?v=4.2.0"
把里面图片url 版本号删除打包就正常了

**Comment by alvin2ye** [comment]
+1

**Comment by pigcan** [comment]
@sorrycc  这个bug我来跟进吧
