### ISSUE TITLE
spmjs.io 无法访问

### ISSUE THREAD

**Issue by wuguanghai45** [spmjs/spm#1344]

**Comment by wuguanghai45** [comment]
502 Bad Gateway

The proxy server received an invalid response from an upstream server. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL:	http://spmjs.io/
Server:	localhost.localdomain
Date:	2015/07/12 01:43:57
Powered by Tengine/2.0.3

**Comment by sorrycc** [comment]
已恢复。
