### ISSUE TITLE
spm doc watch出错

### ISSUE THREAD

**Issue by front-thinking** [spmjs/spm#1347]
安装官方doc一步步配置环境，组件开发部分写代码，结果总是在这里报错，执行spm doc watch 出现error。具体错误如下，从错误信息来看，提示expect.js模块没有安装，可是明明安装了的，非常确定安装了的。spm版本为3.6.6。谁给看看咋回事？
![1](http://i1.tietuku.com/520048df64f5456d.jpg)

![2](http://i1.tietuku.com/7f324a1e53f5f824.jpg)

![3](http://i1.tietuku.com/e760d14c1fd81901.jpg)

**Comment by sorrycc** [comment]
重装下，unpublish 了一个错误的版本。
