### ISSUE TITLE
当css路径较深时，spm server处理css map报404错误

### ISSUE THREAD

**Issue by helloyou2012** [spmjs/spm#1349]
错误Demo见下面项目里的home.html页面：

[https://github.com/helloyou2012/less-loader-test](https://github.com/helloyou2012/less-loader-test)

运行`spm server`，打开home.html报css map的404错误。

**Comment by pigcan** [comment]
是有这个bug

**Comment by helloyou2012** [comment]
在这一行生成的css文件中的map地址已经错了：[https://github.com/spmjs/spm-webpack/blob/master/lib/SPMPlugins.js#L57](https://github.com/spmjs/spm-webpack/blob/master/lib/SPMPlugins.js#L57)。应该是webpack中的问题了。
