### ISSUE TITLE
考虑能支持 sass 么？

### ISSUE THREAD

**Issue by nimojs** [spmjs/spm#1359]
Module parse failed: $CWD/a.scss Line 1: Unexpected token {
You may need an appropriate loader to handle this file type.
| body {
|     background-color: red;
| }
 @ ./index.js 3:0-19

**Comment by sorrycc** [comment]
https://github.com/spmjs/docs/blob/master/zh-cn/project/configuration.md#loader
可以通过自定义 loader 来解决
