### ISSUE TITLE
【急】spm 3.6.10 build 报错 TypeError: Cannot read property 'htmlMinify' of undefined

### ISSUE THREAD

**Issue by Deyoud** [spmjs/spm#1364]
init2.js代码如下
![image](https://cloud.githubusercontent.com/assets/6890457/9105541/50373bec-3c4b-11e5-8ae6-5c936891320a.png)
queryRandom.js代码如下：
![image](https://cloud.githubusercontent.com/assets/6890457/9105555/6b7e0bce-3c4b-11e5-8393-fd6910dd6d3b.png)
执行spm build init2.js报错，如下
![image](https://cloud.githubusercontent.com/assets/6890457/9105407/f68f312c-3c49-11e5-8272-9bf7f4fd55fc.png)

如图：
TypeError: Cannot read property 'htmlMinify' of undefined

这是什么原因呀？

**Comment by sorrycc** [comment]
写个 package.json，至少包含 {"spm": {}}
