### ISSUE TITLE
spm3.6 css压缩的时顺序变了

### ISSUE THREAD

**Issue by zhangping2014** [spmjs/spm#1365]
压缩前
html {
  font-family: sans-serif;
  -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
}
body {
  margin: 0;
}
....
压缩后
hr,img{border:0;}body,figure{margin:0;}.btn-

为啥不是按着 html, body  这个顺序

**Comment by army8735** [comment]
压缩优化，同级tagName互斥，顺序不影响优先级
