### ISSUE TITLE
请教一下 关于 spm 定位的问题

### ISSUE THREAD

**Issue by clarkhan** [spmjs/spm#1368]
之前 spm 是 seajs 的 package manager，现在貌似不是了（有段时间没跟了，或许很久前就不是了？）。

看了下新的 docs，好像没太明白 spm 的问题域。感觉上 spm 现在是一个 module bundler + package manager。打包的部分功能是封装 webpack 让 webpack 更好用吗？本地 spm 打包后，脱离 seajs ，包管理的作用好像和 npm 相近？ 

比如 `npm install rc-menu` + webpack 和 `spm install rc-menu` 都解决了同样的问题，得到相似的结果，是吗？

没找到太多资料，希望有朋友能帮我解惑。谢谢！

**Comment by sorrycc** [comment]
你理解的都是对的，module bundler + package manager 。

**Comment by clarkhan** [comment]
谢谢！

我理解 module bundler 是为了简化了 webpack 的使用，或者屏蔽了 webpack ，给大家方便好用的 module bundler 工具。或许以后出来个更先进的 webpack 2 ，底层就换成了 webpack 2 。 这样理解对吗？

但是 package manager 是为了解决什么问题呢，直接用 npm 呢？

**Comment by alvin2ye** [comment]
@clarkhan 我猜 npm 上有些前端有些后端比较乱. spm 里的都是前端.

不过倒库确实麻烦.

以后是否可能会有:

```
spm install https://www.npmjs.com/package/jquery
``` 
或者干脆

```
spm install https://github.com/jquery/jquery

```

再有有个命令是:
```
spm upgrade

```
学下 rubygem
