### ISSUE TITLE
spm.io 内网源部署问题

### ISSUE THREAD

**Issue by pdap** [spmjs/spm#1373]
我在阿里云主机 一核心 1G内存 1M带宽 的吊丝主机(win2003) 上部署spmio 按照教程部署好之后，执行 npm install 过程无任何报错， 最后按照教程 复制 base.default.yaml 为 base.yaml ，然后执行 npm start 命令 ，此时 cmd窗口一直有闪，cpu 占用直接飙升到100%，在服务器上访问默认的127.0.0.1:3000无反应
![图片](http://img.blog.csdn.net/20150818220052339)

**Comment by sorrycc** [comment]
为啥不用 linux? windows 没试过能否部署。

**Comment by sorrycc** [comment]
看图显示的是搜索没启动成功，直接 `node app.js` 试试是否可用。

**Comment by pdap** [comment]
我1个人非常喜欢linux，不用linux的原因是我的屌丝主机是跟屌丝同事合伙买的，然后就没有然后了，木桶原理你懂的

**Comment by pdap** [comment]
现在问题解决了，按照你说的运行 node app.js ，提示没装sqlite3。。。于是本吊大手一挥，自信的运行了个npm install sqlite3  果然粗来了，擦提示本屌丝 没有vsbuild.exe编译 环境（你麻痹的巨硬啊）;按照提示下载了巨硬的400M的  .NET Framework 2.0 SDK(心疼主机中( ▼-▼ ))，然后重新运行 npm install  sqlite3 命令，貌似很正常（没有那一坨坨红色的警告了）, 然后运行 node app.js  ，出来下图了，一坨坨初始化数据库的东西，然后命令处于监听状态。接着本屌丝自信的打开默认的127.0.0.1:3000，丫的，粗来了。我用行动证明了巨硬系统也是可以跑spmio 内网源server的，下面是我的图图
---
> 提示安装sqlite3
![提示安装sqlite3](http://img.blog.csdn.net/20150821192152496)
> 成功启动
![成功启动](http://img.blog.csdn.net/20150821192434992)
> 高兴
![开心](http://img.blog.csdn.net/20150821192659946)
