### ISSUE TITLE
找不到windows操作系统下spm的cmd脚本

### ISSUE THREAD

**Issue by 74sharlock** [spmjs/spm#1375]
>期望:因为使用webstorm, 我打算添加一个file watcher, 使得我添加||更改seajs模块时自动使用spm命令进行合并压缩等任务. 
>结果:但是npm下面没有找到spm.cmd脚本, 导致无法添加 (node_modules下面有spm模块, 可以手动执行spm命令)
>问题:如果我想使用spm.cmd, 我自己该如何编写?

**Comment by sorrycc** [comment]
试了下，有 cmd 的，不然 windows 下无法执行吧。另外 seajs 模块要用 spm-sea 了，现在的 spm 默认已经不支持 seajs 了。

**Comment by 74sharlock** [comment]
抱歉, 确实有...我眼看花了刚才.

spm-sea是需要单独安装的么?

<code>npm install spm-sea -g</code>

我需要去哪里才能找到spm-sea的文档呢?seajs的官网貌似很久木有更新了.

**Comment by sorrycc** [comment]
考虑换成现在 spm 的这种 standalone 的方式吧，我们内部也都不用 seajs 了。

**Comment by 74sharlock** [comment]
好的, 非常感谢.我去了解下standalone.

**Comment by sorrycc** [comment]
https://github.com/spmjs/docs/tree/master/zh-cn

**Comment by 74sharlock** [comment]
已经找到文档了.
刚才大致看了一下, 觉得有点晕.
打算把我的seajs模块先用npm+browserify全部重构一下, 等熟悉了现有的spm构建模式再尝试.
再次感谢.
