### ISSUE TITLE
关于require的路径问题

### ISSUE THREAD

**Issue by haidao2620** [spmjs/spm#1382]
先说运行环境吧：后端基于node，前端基于arale和spm３；
由于arale又是基于seajs，所以在使用spm模块的时候，require的路径是按照seajs的路径机制加载的,而spm中的依赖模块的require是跟node的一致，因此要先依赖模块配置也写入到sea.config中来，否则直接使用就会出现加载失败的问题，请问下，现在有没有比较好的方式，使得即使不写入到sea.config中来，也能使spm模块中依赖的模块正常工作；

**Comment by pigcan** [comment]
arale的组件不是已经适配到spm3了么
