### ISSUE TITLE
spm包多一层目录问题

### ISSUE THREAD

**Issue by lore-w** [spmjs/spm#1383]
rt，我自己init一个spm的包叫spm-pjax，打包时报错，排查发现包的目录结构为
```
spm_modules\spm-pjax\1.0.7\spm-pjax
```
多了一层spm-pjax目录导致打包失败，包publish一个新的版本还是有同样的问题，1.0.7是spm init完成时就直接publish的，没有做任何修改，install还是一样。

spm版本v3.4.1

**Comment by hotoo** [comment]
试试最新版

**Comment by pigcan** [comment]
试了下 `spm-pjax@1.1.0` 没有问题.

**Comment by lore-w** [comment]
换了spm的版本没有问题了，之前有问题的已经被publish的版本已撤销
