### ISSUE TITLE
spm3.6支持require.async?

### ISSUE THREAD

**Issue by haozileung** [spmjs/spm#1387]
原来的用法require.async在3.6下不能用了，报async 不存在。

是否有其它方法？

**Comment by jaredleechn** [comment]
可以试试使用[load-on-demand](https://github.com/spmjs/examples/tree/spm-webpack/load-on-demand)

**Comment by haozileung** [comment]
嗯嗯，可以用。
不过有个问题：那些子模块的js build出来后的路径可以不可以配置？指在script 里的src属性。

**Comment by jaredleechn** [comment]
异步require的文件路径是随意的，只要是你本地的就可以，但build出来的路径是不可以配置的，默认在dist的根目录下。

如果你使用`require('./moduleA.js')`这种常量方式，那么spm会把`被require的js`打包在一起。

如果你使用了`require([src.name])`这种变量的方式，那么spm会把你本地`所有可能用到的js`全部打包成一个`0.js`，并建立原文件名到模块的名的索引，这样所有模块都打包到一起的话，其实异步require的意义就不是很大了，因为你加载某一个模块的时候，也加载了全部的模块。

**Comment by haozileung** [comment]
感谢解答！
常量变量那个可以理解，一般模块都是在开发阶段就决定好了的，不会用到变量的方式。

关于build出来后的路径，看build出来的代码，在最后加载的时候有个基类变量。应该是来自webpack的output.public path变量，这个不能配置有点奇怪。估计是webpack问题。
参考例子：https://github.com/webpack/webpack/tree/master/examples/code-splitting

**Comment by haozileung** [comment]
我fork了spm-webpack项目，添加了public参数到spm build。问题解决~

**Comment by sorrycc** [comment]
@haozileung 怎么解决的? 发个 pr 上来看看?
