### ISSUE TITLE
spm init时一直出现Existing files here, please run init command in an empty folder!

### ISSUE THREAD

**Issue by polarbear567** [spmjs/spm#1389]
第一次安装spm3后构建成功过，后来不知道怎么回事，打开HTML后，Chrome报如下错误：http://localhost:63342/test_with_seajs_and_spm3/dist/test_with_seajs_and_spm3/1.0.0/static/js/main.dist Failed to load resource: the server responded with a status of 404 (Not Found)
不知道为什么会出现main.dist这个文件

**Comment by jaredleechn** [comment]
spm init是初始化项目目录的时候的命令，如果需要构建请使用spm build，如果需要调试使用spm server，无需引入dist下打包的文件即可动态调试。
