### ISSUE TITLE
spm server 时如果文件没有改动可以加个304吗?  你看每次刷新要9秒多.

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1392]
![image](https://cloud.githubusercontent.com/assets/5401/10627323/9d8e524c-77ea-11e5-9f64-67029f6662e6.png)

**Comment by alvin2ye** [comment]
SPM 不会不维护了吧 ?

**Comment by sorrycc** [comment]
目前由 @pigcan 负责维护。

**Comment by alvin2ye** [comment]
经过反复测试, 居然是我浏览器的问题. 重新安装后正常.
