### ISSUE TITLE
spm执行后，css关联的图片会自动打包过去，但是路径是错误的。差了一个文件夹

### ISSUE THREAD

**Issue by youpinyao** [spmjs/spm#1396]
spm执行后，css关联的图片会自动打包过去，但是路径是错误的。差了一个文件夹，css路径少了../

**Comment by pigcan** [comment]
什么平台

在打包过后所有的图片 都会被构建在 构建目录的 根目录。 相应的引用路径都会被重新修改.

**Comment by youpinyao** [comment]
图片是在我定义路径的根目录，而我css文件是在文件夹css里面，css文件路径是写着background:url(sdfghjkfghjk.jpg);  这是错的，要background:url(../sdfghjkfghjk.jpg);这样才没错

**Comment by youpinyao** [comment]
是window  seajs

**Comment by youpinyao** [comment]
还有构建的路径应该在对应的目录就好，干嘛要放到根目录

**Comment by youpinyao** [comment]
有空回答一下！

**Comment by pigcan** [comment]
windows 平台路径修复上 可能有问题. 本周会处理下.

**Comment by youpinyao** [comment]
好的，谢谢

**Comment by youpinyao** [comment]
还没更新。。。

**Comment by jaredleechn** [comment]
已经修复了，但是还没在npm上release  https://github.com/spmjs/spm-webpack/pull/34
