### ISSUE TITLE
 spm 3.6 支持 windows?

### ISSUE THREAD

**Issue by wpfpizicai** [spmjs/spm#1398]
![image](https://cloud.githubusercontent.com/assets/4327513/10900583/d40d6664-821c-11e5-88eb-e3e5d6d681f0.png)
使用的时候总是报这个错误

**Comment by pigcan** [comment]
现在 spm 在 windows 下 有存在一定的 兼容问题. 本周会集中处理下.

**Comment by jaredleechn** [comment]
@wpfpizicai 能提供下完整的使用场景么，具体是执行哪个命令时报错以及完整的报错信息

**Comment by pigcan** [comment]
已经修复了
