### ISSUE TITLE
jsx2-webpack-loader doesn‘t exist ？

### ISSUE THREAD

**Issue by honger05** [spmjs/spm#1400]
新装的 spm3.6.12

  C:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\spm-webpack\node_modules\jsx2-webpack-loader doesn't exist

**Comment by jaredleechn** [comment]
确认下这个目录下有没有`jsx2-webpack-loader`，没有的话应该是安装出问题了，尝试`uninstall`后再安装
