### ISSUE TITLE
请问最新的版本什么时候发布？现在还是3.6.12

### ISSUE THREAD

**Issue by youpinyao** [spmjs/spm#1401]

**Comment by jaredleechn** [comment]
已经发布了
- spm-webpack@0.8.1 : 增强了windows下的兼容性, 全新的 define 实现，支持了真正意义的差异化构建， 去除了无关依赖，支持 node@4+ .
- spm-webpack-server@0.8.3 ：配合全新的 define ，以及历史依赖的去除.
- 发布spm@3.7.0-beta1
