### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by jiangl1992** [spmjs/spm#1403]
为啥我执行spm publish后，返回是： exit:Permission denied ~

**Comment by jaredleechn** [comment]
- 运行过`spm login`没？
- 看下[源](http://spmjs.io)上是不是已经有其他人上传了这个模块？

**Comment by jiangl1992** [comment]
运行了spm login，而且是登录成功的。
但是去哪里看源 是不是已经有其他人上传过了呢？

**Comment by xuhuan** [comment]
@jiangl1992 spmjs.io上看下是否有同名模块。

**Comment by pigcan** [comment]
可以使用 `spm info 模块名` 来确定.
