### ISSUE TITLE
css 中怎么引入 bootstrap，font-awesom，这类库呢？

### ISSUE THREAD

**Issue by honger05** [spmjs/spm#1404]
````css
@import '~font-awesome';
````

这种都要报错。

另外， spm 中没有 bootstrap 的 css 模块啊。

如何引用这类库呢 ？

**Comment by pigcan** [comment]
一般 写法就会是 js中  require('moduleA')， 或在 项目 less 里面  @import （css） '~moduleA/path/to/css’
