### ISSUE TITLE
不知道怎么回事不能安装 

### ISSUE THREAD

**Issue by kwdiwt** [spmjs/spm#1407]
```
Auser@Mey MINGW64 /h/Project/test
$ npm install -g spm
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated babel-core@5.4.7: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "spm"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "spm"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
```

**Comment by kwdiwt** [comment]
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip

**Comment by kwdiwt** [comment]
cmd下的
'''
C:\Users\chen>npm install -g spm
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN install Couldn't install optional dependency: Unsupported
loadDep:mkdirp-then → req ▐ ╢███████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░loadDep:mkdirp-then → net ▄ ╢███████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░loadDep:mkdinpm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated babel-core@5.4.7: Babel 5 is no longer being maintained. Upgrade to Babel 6.
C:\Users\chen\AppData\Roaming\npm\spm -> C:\Users\chen\AppData\Roaming\npm\node_modules\spm\bin\spm

> phantomjs@1.9.19 install C:\Users\chen\AppData\Roaming\npm\node_modules\spm\node_modules\phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\chen\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TLSWrap.onread (net.js:544:26)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN install:phantomjs@1.9.19 phantomjs@1.9.19 install: `node install.js`
npm WARN install:phantomjs@1.9.19 Exit status 1
C:\Users\chen\AppData\Roaming\npm
└── (empty)

npm WARN EPEERINVALID handlebars-loader@0.1.8 requires a peer of handlebars@>= 1.3.0 < 3 but none was installed.
npm ERR! code 1
'''

**Comment by hotoo** [comment]
```bash
$ npm install -g cnpm --registry=http://registry.npm.taobao.org
$ cnpm i -g spm
```

**Comment by kwdiwt** [comment]
安装好后不能用
![xxx](http://img.vim-cn.com/2d/cfed2c2720bc10054a472ee82deccbbef20637.png)

**Comment by hotoo** [comment]
你本机 Node 版本太低了。

**Comment by kwdiwt** [comment]
嗯 刚才google了下查到原因了 然后再去https://github.com/spmjs/docs/blob/master/zh-cn/setup.md
总算安装好了
