### ISSUE TITLE
有没有计划babel升到6？

### ISSUE THREAD

**Issue by xuhuan** [spmjs/spm#1411]
RT，安装的时候提示如下
![image](https://cloud.githubusercontent.com/assets/1960194/11735184/6ddfc0b2-9ff9-11e5-9144-7daa1a7d21e2.png)

顺带其他的包，3.6.12已经安装不了了。
![image](https://cloud.githubusercontent.com/assets/1960194/11735283/7a975350-9ffa-11e5-8e1c-284283d11bf6.png)

**Comment by wuguanghai45** [comment]
只是警告。。。不影响spm 3.6.12的安装吧。。

**Comment by xuhuan** [comment]
执行了多次，都是出现上面错误后就结束了。
