### ISSUE TITLE
standlone 如何构建tpl,html 静态文件

### ISSUE THREAD

**Issue by becky-guo** [spmjs/spm#1412]
![qq 20151211194155](https://cloud.githubusercontent.com/assets/13389167/11743060/889b6e92-a03f-11e5-94e2-1f93e9f87018.png)
![qq 20151211194111](https://cloud.githubusercontent.com/assets/13389167/11743062/8a5744ae-a03f-11e5-9bdf-e35169dbc837.png)

**Comment by jaredleechn** [comment]
1. 保证spm版本3.6.x
2. 模版文件直接使用 `.tpl` 后缀，`require('*.tpl')`时会自动处理
3. html文件配置在你的package.json里的output里面，具体参考文档

**Comment by becky-guo** [comment]
@jaredleechn  非常感谢,昨天翻文档才知道只支持.tpl的模板文件  改成tpl后好了.
