### ISSUE TITLE
安装spm报错

### ISSUE THREAD

**Issue by xinjingfen** [spmjs/spm#1417]
> phantomjs@1.9.19 install C:\Program Files\nodejs\node_modules\spm\node_modules
	\phantomjs
	> node install.js
	
	PhantomJS not found on PATH
	Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
	ows.zip
	Saving to C:\Users\14060208\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
	.zip
	Using proxy http://10.19.110.31:8080/
	Receiving...
	/
	Error making request.
	Error: read ECONNRESET
	    at exports._errnoException (util.js:746:11)
	    at TCP.onread (net.js:550:26)
	
	Please report this full log at https://github.com/Medium/phantomjs
	npm ERR! Windows_NT 6.1.7601
	npm ERR! argv "node" "C:\\Users\\14060208\\AppData\\Roaming\\npm\\node_modules\\
	npm\\bin\\npm-cli.js" "install" "-g" "spm"
	npm ERR! node v0.12.0
	npm ERR! npm  v2.14.15
	npm ERR! code ELIFECYCLE
	
	npm ERR! phantomjs@1.9.19 install: `node install.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
	npm ERR! This is most likely a problem with the phantomjs package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node install.js
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls phantomjs
	npm ERR! There is likely additional logging output above.
	
	npm ERR! Please include the following file with any support request:
	npm ERR!     C:\Users\14060208\npm-debug.log

**Comment by wuguanghai45** [comment]
phantoms 安装出错。。 现在node 5.0 + 了 升级下node 吧。。 话说spm 貌似已经不维护。。 楼主转投npm + webpack 怀抱吧。。

**Comment by xinjingfen** [comment]
问题解决了，phantomjs没安装，安装phantomjs模块需要用到他专门的cdn

**Comment by jaredleechn** [comment]
@xinjingfen http://npm.taobao.org/
