### ISSUE TITLE
spm doc的时候出错

### ISSUE THREAD

**Issue by carlos121493** [spmjs/spm#1423]
1.spm doc的时候如果有依赖是没有升过tnpm的话，spm doc会失效，
2.另外原来spm的output中可以正确找到引用，升级后output命令无法找到正确引用，比如原来name:'hermes-select',main:'select.js',output:['select.js','dropdown.js'],原来可以require('hermes-select/dropdown');现在升级后require('@alipay/hermes-select/dropdown');不行了require('@alipay/hermes-select');还可以

**Comment by pigcan** [comment]
1. 源迁移公告里面都写明白了， md 文件我们迁移工具是不会去做修复的.  对于 doc 需要手动修复下 md 文件中的引用关系 .

2. 不存在你说的问题. 

测试目录和文件：

![image](https://cloud.githubusercontent.com/assets/848515/12633466/1ef6be18-c5ad-11e5-88c9-ada713f4690c.png)

结果：

![image](https://cloud.githubusercontent.com/assets/848515/12633500/5d5cde08-c5ad-11e5-90c3-16adbe3c9874.png)

![image](https://cloud.githubusercontent.com/assets/848515/12633506/6b0df8d4-c5ad-11e5-9386-6b590de392b7.png)

**Comment by carlos121493** [comment]
你可以试试，组件升级的时候。本地也是改过后才好的。
