### ISSUE TITLE
spmjs.io域名到期了？仓库不能用了。。。

### ISSUE THREAD

**Issue by lidetao** [spmjs/spm#1432]
D:\ENV\webprojects\spm-test> spm install jquery arale-class

         target: http://spmjs.io
         exit: Cannot convert ~ or null to object

**Comment by popomore** [comment]
已经下线了

**Comment by lidetao** [comment]
有其他替代的仓库吗？

**Comment by jaredleechn** [comment]
请使用 npm 来管理自己的模块 http://npmjs.com/
