### ISSUE TITLE
怎么写package.json

### ISSUE THREAD

**Issue by hqyuan** [spmjs/spm#589]
www.abc.com/
/sea-modules
---------seajs
-----------------------seajs.js
---------gallery
---------------------jquery
-----------------------------------jquery.js
/js
---Comm  #公共函数库
------------Common.js
---A # A模块
-------A1
-----------A1_1.js
-----------A1_2.js
---B #B模块
------B1 #功能B1
-------------B1_1.js
-------------B1_2.js
-----B2 #功能B2
------------B2_1.js
------------B2_2.js

我的项目结构如上所示。其中Comm是公共模块，下面也可能还有子目录
A，跟,B是单独的模块。但是呢。A其中的模块有可能会调用B模块里的模块。就是说他们有依赖。

像这种结构 该怎么打包比较好。就是说怎么写那个部署的配置文件(package.json).我的想法是，jquery不合并。其他的模块都合并成一个文件。这样好不好？

谢谢

**Comment by Fengalbean** [comment]
我也遇到跟上面一样的问题，类似的目录结构，不知道如何配置package.json文件

**Comment by jaredleechn** [comment]
@Fengalbean 

https://ant-tool.github.io/webpack-config.html#entry
