### ISSUE TITLE
Arale 从 spm2 迁移到 spm3

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#777]
列下，避免遗漏。
## 基础设施
- [x] base@1.2.0
- [x] class@1.2.0
- [x] events@1.2.0
- [x] widget@1.2.0
## 工具
- [x] cookie@1.1.0
- [x] detector
- [x] Dnd@1.1.0
- [x] Easing@1.1.0
- [x] Iframe-Shim@1.1.0
- [x] Messenger@2.1.0
- [x] Name-Storage@1.1.0
- [x] Position@1.1.0
- [x] Qrcode@1.1.0
- [x] Sticky@1.4.0
- [x] Templatable@0.10.0 `依赖 handlebars`
- [x] Upload@1.2.0 `无测试用例`
## UI 组件
- [x] Autocomplete @1.4.0
- [x] Calendar @1.1.0
- [x] Dialog@1.4.0
- [x] Overlay@1.2.0
- [x] Popup@1.2.0
- [x] Switchable@1.1.0
- [x] Select@0.10.0
- [x] Tip@1.3.0
- [x] Validator@0.10.0
## Alice
- [x] poptip@1.3.0
- [x] select@1.1.0
## Alipay
- [x] alipay-combo
- [x] alipay-object-shim
- [x] alipay-storex
- [x] alipay-xbox

**Comment by v4xyz** [comment]
哥 spm -v 3.3.4 打包arale-calendar(1.1.0、1.1.1、1.1.2)出错啊,提示
AppData\Roaming\npm\node_modules\spm\node_modules\spm-build\node_modules\gulp-spm\lib\plugin下css.js文件54行 depFile.path 未定义，depFile没取到，所有的依赖包都装了。

**Comment by sorrycc** [comment]
https://github.com/spmjs/spm/issues/1168
应该和这个是同一个问题，重装 spm 试试。

**Comment by v4xyz** [comment]
重装spm，还是不能解决，在win8和win7下都是一样的问题，是不是还有什么依赖包需要装的。
![arale-calendar-build-err](https://cloud.githubusercontent.com/assets/5699107/5922025/4bcf03c2-a683-11e4-87a4-d97371c5dca9.jpg)

**Comment by popomore** [comment]
把你打包的项目发出来看看

**Comment by v4xyz** [comment]
http://www.v4xyz.com/content/images/spm3test.7z
我用spm3,打包arale下面其他的包都没问题，就这个calendar怎么也不成功。
spm build --with-deps

**Comment by v4xyz** [comment]
win7和win8下arale-calendar都没有打包成功，今天换到mac平台下打包通过了

**Comment by sorrycc** [comment]
@v4xyz 感谢反馈，重现了。我记录了一个新的 issue 来跟进这个，#1196
