### ISSUE TITLE
spm3 发布日志

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#819]
# spm3 发布通告

很高兴通知各位，更好用的 `spm@3.x` 及其源服务 [spmjs.io](http://spmjs.io) 发布了。
## 缘起

spm 从第一个版本到现在三年了，从 0.x 到 1.x 再到 2.x，定位上从 Sea.js 配套的打包工具到包管理器，已发生了多次大的改变。

> spm 的第一行代码提交是2011年7月9日。那时 npm 刚刚兴起，而 bower、component、browserify 等等还未出现。

相比于 Sea.js 的简洁通用，spm 的包管理和打包机制一直被社区所诟病（我相信有一万个issue吐槽过它），甚至或多或少阻碍了整个社区的发展，这也和我们做生态圈的想法相悖。（可以参考：[spm 的困境](https://github.com/seajs/seajs/issues/959)）

这些年接触 nodejs 时，npm 社区的活跃和便利性给我们很大启发。我们(都)希望在自己的工作中能使用优秀的业界模块（而不是自己开发，或用公司的破框架重构一个），所以我们有了 [Sea.js](http://seajs.org)，有了 spm，有了 [Arale](http://aralejs.org)，这些前端模块化的方案和工具都致力于解决一个问题：**我们如何可以像 npm 一样方便的组织和调用模块，我们如何最小成本地来使用和贡献业界优秀的模块，我们如何能给开发者提供通用的前端模块化解决方案**。

[spm@2.x](https://github.com/spmjs/spm2/issues/12) 在去年发布之后，对上面的问题做了很多解答。实际上，spm2 解决了大多数问题，它在支付宝和很多第三方企业和个人的项目中良好的运转，实践了很多工程问题（比如样式和模板的集成、内网源）。但是它也有很多问题，比如太多约定，比如暴露给开发者的复杂度，比如不通用……

所以我们需要一个更好的 `spm@3.x`。( •̀_•́)ง 
## 定位

新的 `spm@3.x` 从其他包管理方案（browserify、bower、jamjs、component）中汲取了不少优点，在 spm2 的良好基础上，致力于提供一个开放、通用、完善、集成化的**基于浏览器模块生命周期**的包管理工具，包括初始化、编码、本地化调试、文档生成、发布、依赖管理、单元测试、构建、源服务等等功能。

![](https://i.alipayobjects.com/i/localhost/png/201404/2YQxOTYoFp.png)
## 进化

一起来看看 `spm@3.x` 都发生了哪些变化：
1. 精心设计的 [package](http://spmjs.io/documentation/package.json) 规范。
   - 去除 family 字段。打通模块间依赖的壁垒，避免每个 family 下都发布要 jquery 的问题。
   - spm.alias 属性被语义更加明确的 spm.dependencies 属性代替。
   - 添加了 spm.main 属性，实现了单入口，从而使依赖书写更加清爽。
     
     原来你需要这么写：
     
     ``` js
     "alias": {
       "moment": "gallery/moment/2.6.0/moment"
     }
     ```
     
     现在清晰多了：
     
     ``` js
     "dependencies": {
       "moment": "2.6.0"
     }
     ```
   - 去掉了默认的 src 目录等约定规则，这样模块目录结构可以像 npm 模块一样简单随意。
   - 新增 buildArgs 字段，用于模块构建。
2. 编码书写规范从 CMD 规范全面转向 CommonJS，更加通用和开放，不再需要书写烦人的 `define(function(require, module, exports) {})`了，并且可以和 Component 社区进行一定程度的打通。CMD 格式作为调试和上线后的运行时规范继续存在，但基本上对开发者透明了，**我们正在和 CMD 规范告别**。
3. 新的命令行工具 [spm@3.x](https://github.com/spmjs/spm)，我们将原先的功能、常用插件、和在 [apm](https://github.com/spmjs/apm) 中实践出来的通用功能都集成到一起，用于管理一个完整的模块生命周期，包括初始化，完全的本地化调试，测试，发布，构建，文档生成和部署等等功能，All in one。比起其他浏览器包管理工具，功能更加完善贴心，更浏览器，更快(网速:-D)。
4. 基于 [gulp](http://gulpjs.com/) 的构建工具。（spm build）
   - 明显快于 grunt 方式的构建速度。
   - 包管理和构建过程完全分离，源上不存放构建后的代码，发布到源上之前不再需要运行 `spm build`，构建只作为上线前的必要步骤。
   - 简单通用的[配置](http://spmjs.io/documentation/spm-commands#spm-build)让你告别繁琐的 gruntfile，也不再被各种**支付宝潜规则**困扰。
   - 支持 standalone 的打包方式，**无须 Sea.js 环境也可部署使用**。
   - 依旧支持 css、tpl、handlebars 等特殊模块的内嵌。
5. 基于 nodejs 重写的源服务 [spmjs.io](https://github.com/spmjs/spmjs.io/)，用于代替原来用 python 写的 [yuan](https://github.com/spmjs/yuan)，完美适配 spm@3.x，简化的账户体系支持 github 登陆和匿名两种方式，可以很方便部署（适合作为企业级开发的内网源），同时方便了我们的后续维护。我们已部署了一个 [spmjs.io](http://spmjs.io) 作为通用的全网服务。
6. 高端大气的界面以及……英文文档！我们要更加国际化。
   
   ![图](https://i.alipayobjects.com/i/localhost/png/201406/2ofEyeIdLz.png)
7. 大量细节变化不一一絮述。
## 使用

好吧，正式的用起来吧！
### 安装

``` bash
$ npm install spm -g
```

> 会覆盖 spm2，需要共存的请参考[spm 2, 3 共存方案 ](https://github.com/spmjs/spm/wiki/spm-2,-3-%E5%85%B1%E5%AD%98%E6%96%B9%E6%A1%88)。

确保你安装的是 3.x 版本：

``` bash
$ spm -v
3.x.x
```
### 开始试用

直接看官网的上手文档吧：[spmjs.io/documentation](http://spmjs.io/documentation)

> 不要担心英文，这些文档都是中国人写的:-D
## 参与

我们衷心的希望您能一起参与到新版 spm 的开发和使用中来，你可以从以下几个方面入手：
1. 迁移旧的模块。
   
   如果您在使用老的源服务 [https://spmjs.org](https://spmjs.org)，建议进行迁移，可以参考[迁移文档](https://github.com/spmjs/spm/wiki/%E8%BF%81%E7%A7%BB-spm2-%E5%88%B0-spm3) 和使用[迁移工具](https://github.com/spmjs/spm-migrate)。推荐参考已迁移的 Arale 模块如 [Base](https://github.com/aralejs/base/) 的结构。
2. 推广 spm 社区。
   
   由于新的模块规范通用性和开放性的改变，使我们向国外社区的推广有了可能。我们已经用 `pull request` 的方式开始向国外的开源项目推广 spm，目前推广效果还算不错，欢迎加入我们的工作。（[向开源项目推广 spm 的汇总](https://github.com/spmjs/spm/issues/781)）
3. 发布你的模块。
   
   如果你有牛逼好用的前端项目，欢迎引入 spm3，把模块发布到 spmjs.io 上；也可以帮助我们发布一些业界优秀的模块（目前主要是我们团队的几个人在努力的发啊发）。因为去掉了 family，所以 spmjs.io 和 npm 一样，采用**占坑**的方式管理模块，好名字先到先得欢迎抢注（不要滥用哦）。
4. 应用。
   
   在您的个人博客和公司项目中使用 spm3 新方案，能用的东西才会是好东西。遇到任何问题或有什么好想法，及时给我们[提建议](https://github.com/spmjs/spm/issues)。
## 备注
1. 旧版的 spm2 的源服务 [https://spmjs.org](https://spmjs.org) 将和新版的源共存一段时间（预计至少半年），强烈建议老用户进行迁移。
2. 由于 spm2 和 spm3 差异巨大，如果贵公司的文档里有安装 spm2 的文档，请及时修改为`npm install spm@2.x -g`。

相关链接：
- [命令行工具](https://github.com/spmjs/spm)
- [源服务](http://spmjs.io)
- [文档](http://spmjs.io/documentation)
- [源服务源码](https://github.com/spmjs/spmjs.io)
- [spm@3.0 和 spmjs.org 的未来](https://github.com/spmjs/spm/issues/718)
- [向开源项目推广 spm 的汇总](https://github.com/spmjs/spm/issues/781)
- [迁移 spm2 到 spm3](https://github.com/spmjs/spm/wiki/%E8%BF%81%E7%A7%BB-spm2-%E5%88%B0-spm3)
- [spm2、3共存方案](https://github.com/spmjs/spm/wiki/spm-2,-3-%E5%85%B1%E5%AD%98%E6%96%B9%E6%A1%88)

**Comment by liuhaifeng2005** [comment]
请教一下怎么引入自己开发的插件呢？另外我压缩完后，只压缩入口文件，可是我的引用的js文件都没有被压缩，是什么原因呢？

**Comment by ikobe** [comment]
文档好赞！

**Comment by fancyboynet** [comment]
请问哪里有最简单的hello spm3例子呀，没用过spm2,不知道具体如何开始，开发，调试，发布，有没有一个完整实现日常页面开发的小示例呢？

**Comment by sorrycc** [comment]
https://github.com/spmjs/docs
看下这里的文档。

**Comment by iostalk** [comment]
大家怎么看待下面的代码，abc会被打包到一起，而不是运行时才加载

```
if (foo) {
   require("./abc");
}
```

**Comment by sorrycc** [comment]
@iostalk 支持按需加载的：

```javascript
if (foo) {
    require(['./abc']);
}
```

例子：https://github.com/spmjs/examples/tree/spm-webpack/load-on-demand

**Comment by iostalk** [comment]
俺的意思可能没说清楚。。运行时加载，就是根据运行的时候foo的值，确定要不要require('abc');
if (foo) {
    require('./abc');
}
而现在spm打包工具会把abc模块与当前模块打包到一起吧，这里的语义存在问题

**Comment by hotoo** [comment]
打包在一起，但是用到 ./abc 时才会真正执行 ./abc 模块。

**Comment by Coca-code** [comment]
我已经举双手支持了！~

**Comment by wpfpizicai** [comment]
我在使用spm的时候 想把几个页面公用的文件打包成一个文件
spm里提供了两种机智来完成这个事情，一个是使用：vendor,
"vendor": ["jquery", "moment"] 是可以的
另一个是使用common:true；
但是使用common:true，在build的时候总是提示错误，
CommonChunkPlugin:while running in a normal mode ,it's not allowed to use a non-entry chunk (common.js)

不知道是不是我哪里用的不对

**Comment by jaredleechn** [comment]
去 spm 上提一个 issue，然后贴一下你的 package.json 文件，并描述下 spm spm-webpack的版本

2015-12-06 16:33 GMT+08:00 wpfpizicai <notifications@github.com>:

> 我在使用spm的时候 想把几个页面公用的文件打包成一个文件
> spm里提供了两种机智来完成这个事情，一个是使用：vendor,
> "vendor": ["jquery", "moment"] 是可以的
> 另一个是使用common:true；
> 但是使用common:true，在build的时候总是提示错误，
> CommonChunkPlugin:while running in a normal mode ,it's not allowed to use
> a non-entry chunk (common.js)
>
> 不知道是不是我哪里用的不对
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spmjs/spm/issues/819#issuecomment-162286770>.
>



-- 
李加俊(*Jared  Lee*)
Front end Engineer@alipay

**Comment by alphabeter** [comment]
安装了两天的spm都没安装上，一堆错误，然后各种谷歌，就没然后了……
$ npm i spm -g
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated babel-core@5.4.7: Babel 5 is no longer being maintained. Upgrade to Babel 6.
