### ISSUE TITLE
支付宝内部源方案备忘

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#867]
3.1 发布后再做，不急，我先把想到的事写下来。

- 内部源搭建
   * 同步外网源
   * 备份
- 模块部署平台 （caniusespm3package.alipay.im）
   * cdn 状态查看
   * 模块快速部署上线（特殊权限，绿色通道，一键确认，批量上线）
- aspm 工具（相当于 spm [command] --register http://spm.alipay.im）
- Arale & Alice
   * 首页文档基于 spm3 重写
   * 各模块页面重新定向到 spmjs.io/docs/* 下。
- 迁移 Alice 和 Alipay 下的所有模块

**Comment by sorrycc** [comment]
aralejs.org 和 aliceui.org 已切换到 SPM3 。
