### ISSUE TITLE
spm3 开发模块如何断点调试

### ISSUE THREAD

**Issue by cloudcome** [spmjs/spm#926]
目前可以用 seajs-wrap 异步加载开发模块，但无法**断点调试**。

---
1. 使用`debugger`
2. build使用debug文件断点

两种方法的调试效率都非常低。

**Comment by afc163** [comment]
https://github.com/spmjs/spm/wiki/%E8%B0%83%E8%AF%95-CommonJS-%E6%BA%90%E7%A0%81
